from __future__ import annotations

import hashlib
import http.server
import json
import os
import socket
import tempfile
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from subprocess import CompletedProcess
from threading import Event, Thread
from typing import ClassVar, cast
from uuid import UUID

import pytest

from rtsp_proxy.node_runtime import (
    DirectNodeProcessController,
    LinuxNodeSupervisor,
    MediaNodeConfigRenderer,
    MediaNodeSmokeProbe,
    NodeHelperSettings,
    NodeManagementCredentials,
    NodeOperationDeadline,
    NodeProcessSnapshot,
    NodeReaderCredentials,
    NodeRuntimeCommand,
    NodeRuntimePolicy,
    NodeRuntimeSpec,
    NodeSupervisorError,
    RenderedNodeConfig,
    SecureNodeConfigStore,
    SystemdNodeProcessController,
    UnixNodeRuntimeClient,
    UnixNodeSupervisorServer,
)
from rtsp_proxy.nodes import (
    MediaNode,
    NodeHealth,
    NodeRuntimeAction,
    NodeRuntimeObservation,
    NodeState,
)


def runtime_spec(*, node_suffix: int = 1) -> NodeRuntimeSpec:
    return NodeRuntimeSpec(
        node_id=UUID(f"00000000-0000-0000-0000-{node_suffix:012d}"),
        external_port=12000 + node_suffix,
        api_port=13000 + node_suffix,
        metrics_port=14000 + node_suffix,
        desired_revision=3,
        release_id="release-2026.08.12",
        mediamtx_binary_sha256="a" * 64,
    )


def management_credentials() -> NodeManagementCredentials:
    return NodeManagementCredentials(
        username="node-00000000-0000-0000-0000-000000000001",
        password="test-management-password-000000000001",
    )


def reader_credentials() -> NodeReaderCredentials:
    return NodeReaderCredentials(
        username="reader-00000000-0000-0000-0000-000000000001",
        password="test-reader-password-0000000000000001",
    )


def test_renderer_keeps_management_and_rtsp_probe_identities_separate() -> None:
    rendered = MediaNodeConfigRenderer().render(
        runtime_spec(),
        management_credentials(),
        reader_credentials(),
    )

    assert "action: api" in rendered.content
    assert "action: metrics" in rendered.content
    assert "user: reader-" in rendered.content
    assert "action: read\n        path: __rtsp_proxy_runtime_probe" in rendered.content
    management_block, reader_block = rendered.content.split("  - user: reader-", maxsplit=1)
    assert "action: read" not in management_block
    assert "action: api" not in reader_block


def test_renderer_produces_one_loopback_managed_ordinary_rtsp_tcp_node() -> None:
    rendered = MediaNodeConfigRenderer().render(runtime_spec(), management_credentials())

    assert rendered.sha256 == ("dd5cf65c0cfa82d06039af8afc3e26ca08fa41972fa397b16885b78a346fe355")
    assert rendered.content == (
        "# Generated by rtsp-proxy. Do not edit.\n"
        "logLevel: info\n"
        "logDestinations: [stdout]\n"
        "logStructured: true\n"
        "authMethod: internal\n"
        "authInternalUsers:\n"
        "  - user: node-00000000-0000-0000-0000-000000000001\n"
        "    pass: test-management-password-000000000001\n"
        '    ips: ["127.0.0.1", "::1"]\n'
        "    permissions:\n"
        "      - action: api\n"
        "      - action: metrics\n"
        "api: true\n"
        "apiAddress: 127.0.0.1:13001\n"
        "apiEncryption: false\n"
        "apiAllowOrigins: []\n"
        "apiTrustedProxies: []\n"
        "metrics: true\n"
        "metricsAddress: 127.0.0.1:14001\n"
        "metricsEncryption: false\n"
        "metricsAllowOrigins: []\n"
        "metricsTrustedProxies: []\n"
        "pprof: false\n"
        "playback: false\n"
        "rtsp: true\n"
        "rtspTransports: [tcp]\n"
        'rtspEncryption: "no"\n'
        "rtspAddress: :12001\n"
        "rtspAuthMethods: [basic]\n"
        "rtspTrustedProxies: []\n"
        "rtmp: false\n"
        "hls: false\n"
        "webrtc: false\n"
        "srt: false\n"
        "moq: false\n"
        "paths: {}\n"
    )
    assert "rtsps" not in rendered.content.lower()
    assert "udp" not in rendered.content.lower()


def test_runtime_command_is_closed_over_an_exact_node_spec() -> None:
    spec = runtime_spec()

    command = NodeRuntimeCommand.for_node(NodeRuntimeAction.PROVISION_START, spec)

    assert command.action is NodeRuntimeAction.PROVISION_START
    assert command.spec == spec
    assert command.config is None


def test_runtime_commands_cannot_smuggle_a_control_plane_generated_config() -> None:
    spec = runtime_spec()
    rendered = MediaNodeConfigRenderer().render(spec, management_credentials())

    with pytest.raises(ValueError, match="runtime_config_not_allowed"):
        NodeRuntimeCommand(
            action=NodeRuntimeAction.PROVISION_START,
            spec=spec,
            config=rendered,
        )


def test_secure_config_store_atomically_installs_exact_node_file(tmp_path: Path) -> None:
    root = tmp_path / "nodes"
    root.mkdir(mode=0o700)
    spec = runtime_spec()
    rendered = MediaNodeConfigRenderer().render(spec, management_credentials())
    store = SecureNodeConfigStore(root=root)

    installed = store.install(spec, rendered, credentials=management_credentials())

    assert installed == root / str(spec.node_id) / "mediamtx.yml"
    assert installed.read_text(encoding="utf-8") == rendered.content
    assert installed.stat().st_mode & 0o777 == 0o600
    assert installed.parent.stat().st_mode & 0o777 == 0o700
    assert tuple(root.rglob("*.tmp")) == ()


def test_secure_config_store_pins_release_binary_and_rotates_private_credentials(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes-pinned"
    root.mkdir(mode=0o700)
    binary = tmp_path / "release" / "bin" / "mediamtx"
    binary.parent.mkdir(parents=True)
    binary.write_bytes(b"pinned-media-binary")
    spec = NodeRuntimeSpec(
        node_id=runtime_spec().node_id,
        external_port=12001,
        api_port=13001,
        metrics_port=14001,
        desired_revision=1,
        release_id="release-2026.08.12",
        mediamtx_binary_sha256=hashlib.sha256(b"pinned-media-binary").hexdigest(),
    )
    store = SecureNodeConfigStore(root=root, binary_path=binary)

    first_rendered, first_credentials = store.provision(spec)
    second_rendered, second_credentials = store.provision(spec)

    node_root = root / str(spec.node_id)
    assert (node_root / "runtime.env").read_text() == (f"RTSP_PROXY_MEDIAMTX_BINARY={binary}\n")
    assert (node_root / "runtime.env").stat().st_mode & 0o777 == 0o600
    assert (node_root / "management.json").stat().st_mode & 0o777 == 0o600
    assert (node_root / "reader.json").stat().st_mode & 0o777 == 0o600
    assert first_credentials != second_credentials
    assert first_rendered.sha256 != second_rendered.sha256
    assert store.credentials(spec) == second_credentials
    assert store.reader_credentials(spec) is not None


@pytest.mark.skipif(os.geteuid() == 0, reason="requires a non-root test process")
def test_secure_config_store_rejects_a_root_owned_contract_with_wrong_owner(
    tmp_path: Path,
) -> None:
    root = tmp_path / "wrong-owner"
    root.mkdir(mode=0o700)
    with pytest.raises(ValueError, match="node_config_root_unsafe"):
        SecureNodeConfigStore(root=root, owner_uid=0).provision(runtime_spec())


def test_secure_config_store_refuses_a_symlinked_node_directory(tmp_path: Path) -> None:
    root = tmp_path / "nodes"
    root.mkdir(mode=0o700)
    escaped = tmp_path / "escaped"
    escaped.mkdir()
    spec = runtime_spec()
    (root / str(spec.node_id)).symlink_to(escaped, target_is_directory=True)

    with pytest.raises(ValueError, match="node_config_directory_unsafe"):
        SecureNodeConfigStore(root=root).install(
            spec,
            MediaNodeConfigRenderer().render(spec, management_credentials()),
            credentials=management_credentials(),
        )

    assert tuple(escaped.iterdir()) == ()


def test_runtime_spec_rejects_overlapping_or_non_loopback_management_ports() -> None:
    with pytest.raises(ValueError, match="node_ports_not_unique"):
        NodeRuntimeSpec(
            node_id=UUID("00000000-0000-0000-0000-000000000001"),
            external_port=12000,
            api_port=12000,
            metrics_port=14000,
            desired_revision=1,
            release_id="release-1",
            mediamtx_binary_sha256="a" * 64,
        )


@pytest.mark.parametrize(
    ("changes", "error"),
    (
        ({"external_port": 0}, "node_port_invalid"),
        ({"desired_revision": 0}, "node_desired_revision_invalid"),
        ({"release_id": ""}, "node_release_id_invalid"),
        ({"mediamtx_binary_sha256": "A" * 64}, "node_binary_sha256_invalid"),
    ),
)
def test_runtime_spec_rejects_noncanonical_identity(
    changes: dict[str, object],
    error: str,
) -> None:
    values: dict[str, object] = {
        "node_id": runtime_spec().node_id,
        "external_port": 12001,
        "api_port": 13001,
        "metrics_port": 14001,
        "desired_revision": 1,
        "release_id": "release-1",
        "mediamtx_binary_sha256": "a" * 64,
    }
    values.update(changes)

    with pytest.raises(ValueError, match=error):
        NodeRuntimeSpec(**values)  # type: ignore[arg-type]


def test_rendered_config_requires_a_final_newline_and_matching_digest() -> None:
    with pytest.raises(ValueError, match="node_config_final_newline_required"):
        RenderedNodeConfig.from_content("paths: {}")

    with pytest.raises(ValueError, match="node_config_digest_mismatch"):
        root = Path(tempfile.mkdtemp(prefix="rtsp-node-", dir="/tmp"))
        try:
            root.chmod(0o750)
            SecureNodeConfigStore(root=root).install(
                runtime_spec(),
                RenderedNodeConfig(content="paths: {}\n", sha256="0" * 64),
                credentials=management_credentials(),
            )
        finally:
            root.rmdir()


def test_runtime_command_never_carries_management_credentials() -> None:
    assert (
        NodeRuntimeCommand(
            action=NodeRuntimeAction.PROVISION_START,
            spec=runtime_spec(),
        ).config
        is None
    )


def test_process_snapshot_rejects_partial_or_stale_identity() -> None:
    with pytest.raises(ValueError, match="active_node_process_identity_incomplete"):
        NodeProcessSnapshot(
            active=True,
            pid=1,
            process_start_ticks=None,
            boot_id=None,
            executable_sha256=None,
        )
    with pytest.raises(ValueError, match="inactive_node_process_has_identity"):
        NodeProcessSnapshot(
            active=False,
            pid=1,
            process_start_ticks=None,
            boot_id=None,
            executable_sha256=None,
        )


def test_secure_store_rejects_relative_or_writable_roots_and_wrong_node_mode(
    tmp_path: Path,
) -> None:
    with pytest.raises(ValueError, match="node_config_root_must_be_absolute"):
        SecureNodeConfigStore(root=Path("relative"))

    writable = tmp_path / "writable"
    writable.mkdir(mode=0o777)
    writable.chmod(0o777)
    with pytest.raises(ValueError, match="node_config_root_unsafe"):
        SecureNodeConfigStore(root=writable).install(
            runtime_spec(),
            MediaNodeConfigRenderer().render(runtime_spec(), management_credentials()),
            credentials=management_credentials(),
        )

    root = tmp_path / "nodes-unsafe"
    root.mkdir(mode=0o700)
    node = root / str(runtime_spec().node_id)
    node.mkdir(mode=0o750)
    with pytest.raises(ValueError, match="node_config_directory_unsafe"):
        SecureNodeConfigStore(root=root).install(
            runtime_spec(),
            MediaNodeConfigRenderer().render(runtime_spec(), management_credentials()),
            credentials=management_credentials(),
        )


class HealthySmokeProbe:
    def check(
        self,
        spec: NodeRuntimeSpec,
        credentials: NodeManagementCredentials,
        deadline: object | None = None,
    ) -> None:
        assert spec == runtime_spec()
        assert credentials.username.startswith("node-")


class RecordingProcessController:
    def __init__(self) -> None:
        self.commands: list[tuple[NodeRuntimeAction, UUID]] = []

    def execute(
        self,
        action: NodeRuntimeAction,
        spec: NodeRuntimeSpec,
        deadline: object | None = None,
    ) -> NodeProcessSnapshot:
        self.commands.append((action, spec.node_id))
        stopped = action in {NodeRuntimeAction.STOP, NodeRuntimeAction.DELETE}
        return NodeProcessSnapshot(
            active=not stopped,
            pid=None if stopped else 1234,
            process_start_ticks=None if stopped else 5678,
            boot_id=None
            if stopped
            else UUID("10000000-0000-0000-0000-000000000001"),
            executable_sha256=None if stopped else "a" * 64,
        )


class FailingSmokeProbe:
    def check(
        self,
        spec: NodeRuntimeSpec,
        credentials: NodeManagementCredentials,
        deadline: object | None = None,
    ) -> None:
        raise NodeSupervisorError("node_api_smoke_failed")


class InactiveProcessController:
    def __init__(self) -> None:
        self.commands: list[NodeRuntimeAction] = []

    def execute(
        self,
        action: NodeRuntimeAction,
        spec: NodeRuntimeSpec,
        deadline: object | None = None,
    ) -> NodeProcessSnapshot:
        self.commands.append(action)
        return NodeProcessSnapshot(
            active=False,
            pid=None,
            process_start_ticks=None,
            boot_id=None,
            executable_sha256=None,
        )


class IndeterminateStartProcessController(InactiveProcessController):
    def execute(
        self,
        action: NodeRuntimeAction,
        spec: NodeRuntimeSpec,
        deadline: object | None = None,
    ) -> NodeProcessSnapshot:
        self.commands.append(action)
        if action is NodeRuntimeAction.PROVISION_START:
            raise NodeSupervisorError("systemd_node_command_failed")
        return NodeProcessSnapshot(
            active=False,
            pid=None,
            process_start_ticks=None,
            boot_id=None,
            executable_sha256=None,
        )


class EventuallyHealthySmokeProbe:
    def __init__(self) -> None:
        self.calls = 0

    def check(
        self,
        spec: NodeRuntimeSpec,
        credentials: NodeManagementCredentials,
        deadline: object | None = None,
    ) -> None:
        self.calls += 1
        if self.calls == 1:
            raise NodeSupervisorError("node_api_smoke_failed")


def test_supervisor_provisions_smokes_and_binds_the_applied_identity(tmp_path: Path) -> None:
    root = tmp_path / "nodes"
    root.mkdir(mode=0o700)
    process = RecordingProcessController()
    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root),
        process=process,
        smoke=HealthySmokeProbe(),
        port_is_bindable=lambda port: False,
        sleep=lambda seconds: None,
    )
    command = NodeRuntimeCommand.for_node(
        NodeRuntimeAction.PROVISION_START,
        runtime_spec(),
    )

    observation = supervisor.execute(command)

    assert process.commands == [
        (NodeRuntimeAction.PROVISION_START, runtime_spec().node_id),
        (NodeRuntimeAction.OBSERVE, runtime_spec().node_id),
    ]
    assert observation.state is NodeState.RUNNING
    assert observation.health is NodeHealth.HEALTHY
    assert observation.management_fresh is True
    assert observation.config_compatible is True
    assert observation.applied_revision == 3
    assert observation.process_id == 1234
    assert observation.process_start_ticks == 5678
    assert observation.process_boot_id == UUID("10000000-0000-0000-0000-000000000001")
    assert observation.config_sha256 is not None
    assert observation.release_id == "release-2026.08.12"


def test_supervisor_stop_requires_process_and_all_three_listeners_to_be_gone(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes"
    root.mkdir(mode=0o700)
    process = RecordingProcessController()
    observed_ports: list[int] = []

    def port_is_bindable(port: int) -> bool:
        observed_ports.append(port)
        return True

    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root),
        process=process,
        smoke=HealthySmokeProbe(),
        port_is_bindable=port_is_bindable,
    )

    observation = supervisor.execute(
        NodeRuntimeCommand.for_node(NodeRuntimeAction.STOP, runtime_spec())
    )

    assert observation.state is NodeState.STOPPED
    assert observation.health is NodeHealth.UNKNOWN
    assert observed_ports == [12001, 13001, 14001]


def test_supervisor_stop_waits_for_all_three_listeners_to_release(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes-stop-convergence"
    root.mkdir(mode=0o700)
    availability = iter((False, True, True, True, True, True))
    observed_ports: list[int] = []
    sleeps: list[float] = []

    def port_is_bindable(port: int) -> bool:
        observed_ports.append(port)
        return next(availability)

    observation = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root),
        process=RecordingProcessController(),
        smoke=HealthySmokeProbe(),
        port_is_bindable=port_is_bindable,
        sleep=sleeps.append,
    ).execute(NodeRuntimeCommand.for_node(NodeRuntimeAction.STOP, runtime_spec()))

    assert observation.state is NodeState.STOPPED
    assert observed_ports == [12001, 13001, 14001, 12001, 13001, 14001]
    assert sleeps == [0.05]


def test_failed_start_smoke_stops_only_that_exact_process(tmp_path: Path) -> None:
    root = tmp_path / "nodes"
    root.mkdir(mode=0o700)
    process = RecordingProcessController()
    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root),
        process=process,
        smoke=FailingSmokeProbe(),
        port_is_bindable=lambda port: True,
        smoke_attempts=2,
        sleep=lambda seconds: None,
    )

    with pytest.raises(NodeSupervisorError, match="node_api_smoke_failed"):
        supervisor.execute(
            NodeRuntimeCommand.for_node(
                NodeRuntimeAction.PROVISION_START,
                runtime_spec(),
            )
        )

    assert process.commands == [
        (NodeRuntimeAction.PROVISION_START, runtime_spec().node_id),
        (NodeRuntimeAction.STOP, runtime_spec().node_id),
    ]


def test_observe_is_read_only_for_inactive_or_temporarily_unhealthy_nodes(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes-observe"
    root.mkdir(mode=0o700)
    spec = runtime_spec()
    store = SecureNodeConfigStore(root=root)
    store.install(
        spec,
        MediaNodeConfigRenderer().render(spec, management_credentials()),
        credentials=management_credentials(),
    )
    inactive = InactiveProcessController()
    inactive_supervisor = LinuxNodeSupervisor(
        config_store=store,
        process=inactive,
        smoke=HealthySmokeProbe(),
        port_is_bindable=lambda port: True,
    )

    stopped = inactive_supervisor.execute(
        NodeRuntimeCommand.for_node(NodeRuntimeAction.OBSERVE, spec)
    )

    assert stopped.state is NodeState.STOPPED
    assert inactive.commands == [NodeRuntimeAction.OBSERVE]

    active = RecordingProcessController()
    unhealthy_supervisor = LinuxNodeSupervisor(
        config_store=store,
        process=active,
        smoke=FailingSmokeProbe(),
        port_is_bindable=lambda port: False,
    )
    with pytest.raises(NodeSupervisorError, match="node_api_smoke_failed"):
        unhealthy_supervisor.execute(NodeRuntimeCommand.for_node(NodeRuntimeAction.OBSERVE, spec))
    assert active.commands == [(NodeRuntimeAction.OBSERVE, spec.node_id)]


def test_indeterminate_start_is_converged_to_verified_stopped_state(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes-indeterminate"
    root.mkdir(mode=0o700)
    process = IndeterminateStartProcessController()
    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root),
        process=process,
        smoke=HealthySmokeProbe(),
        port_is_bindable=lambda port: True,
    )

    with pytest.raises(NodeSupervisorError, match="systemd_node_command_failed"):
        supervisor.execute(
            NodeRuntimeCommand.for_node(NodeRuntimeAction.PROVISION_START, runtime_spec())
        )

    assert process.commands == [
        NodeRuntimeAction.PROVISION_START,
        NodeRuntimeAction.STOP,
    ]


def test_supervisor_retries_transient_smoke_without_restarting(tmp_path: Path) -> None:
    root = tmp_path / "nodes-retry"
    root.mkdir(mode=0o700)
    process = RecordingProcessController()
    smoke = EventuallyHealthySmokeProbe()
    delays: list[float] = []
    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root),
        process=process,
        smoke=smoke,
        port_is_bindable=lambda port: False,
        smoke_attempts=2,
        retry_delay_seconds=0.1,
        sleep=delays.append,
    )

    observation = supervisor.execute(
        NodeRuntimeCommand.for_node(NodeRuntimeAction.PROVISION_START, runtime_spec())
    )

    assert observation.health is NodeHealth.HEALTHY
    assert smoke.calls == 2
    assert delays == [0.1]
    assert process.commands == [
        (NodeRuntimeAction.PROVISION_START, runtime_spec().node_id),
        (NodeRuntimeAction.OBSERVE, runtime_spec().node_id),
    ]


def test_supervisor_refuses_missing_or_tampered_config_before_process_mutation(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes-config"
    root.mkdir(mode=0o700)
    process = RecordingProcessController()
    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root),
        process=process,
        smoke=HealthySmokeProbe(),
        port_is_bindable=lambda port: False,
    )

    with pytest.raises(NodeSupervisorError, match="node_config_not_applied"):
        supervisor.execute(NodeRuntimeCommand.for_node(NodeRuntimeAction.START, runtime_spec()))
    assert process.commands == []


def test_supervisor_stops_a_process_that_never_becomes_active(tmp_path: Path) -> None:
    root = tmp_path / "nodes-inactive-start"
    root.mkdir(mode=0o700)

    class InactiveStartProcess(RecordingProcessController):
        def execute(
            self,
            action: NodeRuntimeAction,
            spec: NodeRuntimeSpec,
            deadline: object | None = None,
        ) -> NodeProcessSnapshot:
            self.commands.append((action, spec.node_id))
            return NodeProcessSnapshot(
                active=False,
                pid=None,
                process_start_ticks=None,
                boot_id=None,
                executable_sha256=None,
            )

    process = InactiveStartProcess()
    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root),
        process=process,
        smoke=HealthySmokeProbe(),
        port_is_bindable=lambda port: True,
    )

    with pytest.raises(NodeSupervisorError, match="node_process_not_active"):
        supervisor.execute(
            NodeRuntimeCommand.for_node(
                NodeRuntimeAction.PROVISION_START,
                runtime_spec(),
            )
        )

    assert process.commands == [
        (NodeRuntimeAction.PROVISION_START, runtime_spec().node_id),
        (NodeRuntimeAction.STOP, runtime_spec().node_id),
    ]


class WrongReleaseProcessController(RecordingProcessController):
    def execute(
        self,
        action: NodeRuntimeAction,
        spec: NodeRuntimeSpec,
        deadline: object | None = None,
    ) -> NodeProcessSnapshot:
        snapshot = super().execute(action, spec, deadline)
        if not snapshot.active:
            return snapshot
        return NodeProcessSnapshot(
            active=True,
            pid=snapshot.pid,
            process_start_ticks=snapshot.process_start_ticks,
            boot_id=snapshot.boot_id,
            executable_sha256="d" * 64,
        )


def test_supervisor_stops_a_process_with_the_wrong_release_identity(tmp_path: Path) -> None:
    root = tmp_path / "nodes-release"
    root.mkdir(mode=0o700)
    process = WrongReleaseProcessController()
    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root),
        process=process,
        smoke=HealthySmokeProbe(),
        port_is_bindable=lambda port: True,
    )

    with pytest.raises(NodeSupervisorError, match="node_process_release_mismatch"):
        supervisor.execute(
            NodeRuntimeCommand.for_node(
                NodeRuntimeAction.PROVISION_START,
                runtime_spec(),
            )
        )

    assert process.commands[-1] == (NodeRuntimeAction.STOP, runtime_spec().node_id)


def test_supervisor_stop_rejects_a_listener_that_survived_the_process(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes-listener"
    root.mkdir(mode=0o700)
    process = RecordingProcessController()
    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root),
        process=process,
        smoke=HealthySmokeProbe(),
        port_is_bindable=lambda port: False,
    )

    with pytest.raises(NodeSupervisorError, match="node_listener_still_active"):
        supervisor.execute(NodeRuntimeCommand.for_node(NodeRuntimeAction.STOP, runtime_spec()))


def test_systemd_adapter_can_only_address_the_exact_uuid_instance(tmp_path: Path) -> None:
    calls: list[tuple[str, ...]] = []
    proc_root = tmp_path / "proc"
    proc_root.mkdir()

    def run(arguments: tuple[str, ...], timeout: float) -> CompletedProcess[str]:
        calls.append(arguments)
        if "show" in arguments:
            return CompletedProcess(
                arguments,
                0,
                "ActiveState=inactive\nMainPID=0\n",
                "",
            )
        return CompletedProcess(arguments, 0, "", "")

    controller = SystemdNodeProcessController(
        systemctl=Path("/usr/bin/systemctl"),
        run=run,
        proc_root=proc_root,
    )

    snapshot = controller.execute(NodeRuntimeAction.STOP, runtime_spec())

    unit = "rtsp-proxy-media@00000000-0000-0000-0000-000000000001.service"
    assert calls == [
        ("/usr/bin/systemctl", "--no-ask-password", "stop", unit),
        (
            "/usr/bin/systemctl",
            "--no-pager",
            "show",
            unit,
            "--property=ActiveState",
            "--property=MainPID",
        ),
    ]
    assert snapshot.active is False


def test_systemd_stop_reserves_time_for_status_and_listener_proof(tmp_path: Path) -> None:
    timeouts: list[float] = []
    current = [0.0]

    def run(arguments: tuple[str, ...], timeout: float) -> CompletedProcess[str]:
        timeouts.append(timeout)
        if "stop" in arguments:
            current[0] = 16.0
            return CompletedProcess(arguments, 0, "", "")
        return CompletedProcess(
            arguments,
            0,
            "ActiveState=inactive\nMainPID=0\n",
            "",
        )

    snapshot = SystemdNodeProcessController(
        systemctl=Path("/usr/bin/systemctl"),
        run=run,
        proc_root=tmp_path / "proc",
    ).execute(
        NodeRuntimeAction.STOP,
        runtime_spec(),
        NodeOperationDeadline(
            expires_monotonic=25,
            monotonic=lambda: current[0],
        ),
    )

    assert snapshot.active is False
    assert timeouts == [20, 9]


def test_systemd_adapter_binds_active_pid_start_boot_and_binary_identity(
    tmp_path: Path,
) -> None:
    binary = tmp_path / "mediamtx"
    binary.write_bytes(b"verified-binary")
    proc_root = tmp_path / "proc"
    process_root = proc_root / "1234"
    process_root.mkdir(parents=True)
    (proc_root / "sys/kernel/random").mkdir(parents=True)
    (proc_root / "sys/kernel/random/boot_id").write_text(
        "10000000-0000-0000-0000-000000000001\n",
        encoding="ascii",
    )
    stat_fields = ["S", *("0" for _ in range(18)), "5678"]
    (process_root / "stat").write_text(
        f"1234 (mediamtx worker) {' '.join(stat_fields)}\n",
        encoding="ascii",
    )
    (process_root / "exe").symlink_to(binary)

    def run(arguments: tuple[str, ...], timeout: float) -> CompletedProcess[str]:
        return CompletedProcess(
            arguments,
            0,
            "ActiveState=active\nMainPID=1234\n",
            "",
        )

    snapshot = SystemdNodeProcessController(
        systemctl=Path("/usr/bin/systemctl"),
        run=run,
        proc_root=proc_root,
    ).execute(NodeRuntimeAction.OBSERVE, runtime_spec())

    assert snapshot == NodeProcessSnapshot(
        active=True,
        pid=1234,
        process_start_ticks=5678,
        boot_id=UUID("10000000-0000-0000-0000-000000000001"),
        executable_sha256=hashlib.sha256(b"verified-binary").hexdigest(),
    )


def test_systemd_start_waits_for_env_to_exec_the_pinned_media_binary(
    tmp_path: Path,
) -> None:
    transient = NodeProcessSnapshot(
        active=True,
        pid=1234,
        process_start_ticks=5678,
        boot_id=UUID("10000000-0000-0000-0000-000000000001"),
        executable_sha256="e" * 64,
    )
    expected = NodeProcessSnapshot(
        active=True,
        pid=1234,
        process_start_ticks=5678,
        boot_id=UUID("10000000-0000-0000-0000-000000000001"),
        executable_sha256="a" * 64,
    )
    identities = iter(
        (
            NodeSupervisorError("node_process_identity_unavailable"),
            transient,
            expected,
        )
    )
    sleeps: list[float] = []

    class ExecTransitionController(SystemdNodeProcessController):
        def _read_process_identity(self, pid: int) -> NodeProcessSnapshot:
            assert pid == 1234
            identity = next(identities)
            if isinstance(identity, NodeSupervisorError):
                raise identity
            return identity

    def run(arguments: tuple[str, ...], timeout: float) -> CompletedProcess[str]:
        return CompletedProcess(
            arguments,
            0,
            "ActiveState=active\nMainPID=1234\n" if "show" in arguments else "",
            "",
        )

    snapshot = ExecTransitionController(
        systemctl=Path("/usr/bin/systemctl"),
        run=run,
        proc_root=tmp_path / "proc",
        sleep=sleeps.append,
    ).execute(NodeRuntimeAction.PROVISION_START, runtime_spec())

    assert snapshot == expected
    assert sleeps == [0.01, 0.01]


def test_systemd_start_rejects_identity_change_during_exec_transition(
    tmp_path: Path,
) -> None:
    identities = iter(
        (
            NodeProcessSnapshot(
                active=True,
                pid=1234,
                process_start_ticks=5678,
                boot_id=UUID("10000000-0000-0000-0000-000000000001"),
                executable_sha256="e" * 64,
            ),
            NodeProcessSnapshot(
                active=True,
                pid=1234,
                process_start_ticks=8765,
                boot_id=UUID("10000000-0000-0000-0000-000000000001"),
                executable_sha256="a" * 64,
            ),
        )
    )

    class ReplacedProcessController(SystemdNodeProcessController):
        def _read_process_identity(self, pid: int) -> NodeProcessSnapshot:
            assert pid == 1234
            return next(identities)

    def run(arguments: tuple[str, ...], timeout: float) -> CompletedProcess[str]:
        return CompletedProcess(
            arguments,
            0,
            "ActiveState=active\nMainPID=1234\n" if "show" in arguments else "",
            "",
        )

    with pytest.raises(NodeSupervisorError, match="systemd_node_identity_changed"):
        ReplacedProcessController(
            systemctl=Path("/usr/bin/systemctl"),
            run=run,
            proc_root=tmp_path / "proc",
            sleep=lambda seconds: None,
        ).execute(NodeRuntimeAction.START, runtime_spec())


def test_systemd_start_returns_wrong_release_identity_after_bounded_wait(
    tmp_path: Path,
) -> None:
    transient = NodeProcessSnapshot(
        active=True,
        pid=1234,
        process_start_ticks=5678,
        boot_id=UUID("10000000-0000-0000-0000-000000000001"),
        executable_sha256="e" * 64,
    )

    class WrongReleaseController(SystemdNodeProcessController):
        _EXEC_TRANSITION_ATTEMPTS = 2

        def _read_process_identity(self, pid: int) -> NodeProcessSnapshot:
            assert pid == 1234
            return transient

    def run(arguments: tuple[str, ...], timeout: float) -> CompletedProcess[str]:
        return CompletedProcess(
            arguments,
            0,
            "ActiveState=active\nMainPID=1234\n" if "show" in arguments else "",
            "",
        )

    snapshot = WrongReleaseController(
        systemctl=Path("/usr/bin/systemctl"),
        run=run,
        proc_root=tmp_path / "proc",
        sleep=lambda seconds: None,
    ).execute(NodeRuntimeAction.START, runtime_spec())

    assert snapshot == transient


def test_supervisor_rechecks_process_identity_after_smoke(tmp_path: Path) -> None:
    root = tmp_path / "nodes-identity-bracket"
    root.mkdir(mode=0o700)
    spec = runtime_spec()
    store = SecureNodeConfigStore(root=root)
    store.install(
        spec,
        MediaNodeConfigRenderer().render(spec, management_credentials()),
        credentials=management_credentials(),
    )

    class ReplacedProcessController(RecordingProcessController):
        def execute(
            self,
            action: NodeRuntimeAction,
            spec: NodeRuntimeSpec,
            deadline: object | None = None,
        ) -> NodeProcessSnapshot:
            snapshot = super().execute(action, spec, deadline)
            if action is NodeRuntimeAction.OBSERVE and snapshot.active:
                return NodeProcessSnapshot(
                    active=True,
                    pid=4321,
                    process_start_ticks=8765,
                    boot_id=snapshot.boot_id,
                    executable_sha256=snapshot.executable_sha256,
                )
            return snapshot

    process = ReplacedProcessController()
    supervisor = LinuxNodeSupervisor(
        config_store=store,
        process=process,
        smoke=HealthySmokeProbe(),
        port_is_bindable=lambda port: True,
    )

    with pytest.raises(NodeSupervisorError, match="node_process_identity_changed"):
        supervisor.execute(NodeRuntimeCommand.for_node(NodeRuntimeAction.START, spec))

    assert process.commands == [
        (NodeRuntimeAction.START, spec.node_id),
        (NodeRuntimeAction.OBSERVE, spec.node_id),
        (NodeRuntimeAction.STOP, spec.node_id),
    ]


def test_observe_rechecks_identity_without_mutating_the_process(tmp_path: Path) -> None:
    root = tmp_path / "nodes-observe-identity"
    root.mkdir(mode=0o700)
    spec = runtime_spec()
    store = SecureNodeConfigStore(root=root)
    store.install(
        spec,
        MediaNodeConfigRenderer().render(spec, management_credentials()),
        credentials=management_credentials(),
    )

    class ReplacedProcessController(RecordingProcessController):
        def execute(
            self,
            action: NodeRuntimeAction,
            spec: NodeRuntimeSpec,
                deadline: object | None = None,
            ) -> NodeProcessSnapshot:
            snapshot = super().execute(action, spec, deadline)
            if len(self.commands) == 2:
                return NodeProcessSnapshot(
                    active=True,
                    pid=4321,
                    process_start_ticks=8765,
                    boot_id=snapshot.boot_id,
                    executable_sha256=snapshot.executable_sha256,
                )
            return snapshot

    process = ReplacedProcessController()
    supervisor = LinuxNodeSupervisor(
        config_store=store,
        process=process,
        smoke=HealthySmokeProbe(),
        port_is_bindable=lambda port: False,
    )

    with pytest.raises(NodeSupervisorError, match="node_process_identity_changed"):
        supervisor.execute(NodeRuntimeCommand.for_node(NodeRuntimeAction.OBSERVE, spec))

    assert process.commands == [
        (NodeRuntimeAction.OBSERVE, spec.node_id),
        (NodeRuntimeAction.OBSERVE, spec.node_id),
    ]


def test_systemd_adapter_rejects_unsafe_path_command_failure_and_bad_status(
    tmp_path: Path,
) -> None:
    with pytest.raises(ValueError, match="systemctl_path_must_be_absolute"):
        SystemdNodeProcessController(systemctl=Path("systemctl"))

    def failed(arguments: tuple[str, ...], timeout: float) -> CompletedProcess[str]:
        return CompletedProcess(arguments, 1, "", "secret diagnostic")

    with pytest.raises(NodeSupervisorError, match="systemd_node_command_failed"):
        SystemdNodeProcessController(
            systemctl=Path("/usr/bin/systemctl"),
            run=failed,
            proc_root=tmp_path,
        ).execute(NodeRuntimeAction.START, runtime_spec())

    for output, error in (
        ("ActiveState=inactive\nActiveState=inactive\nMainPID=0\n", "status_invalid"),
        ("ActiveState=inactive\nMainPID=12\n", "inactive_node_has_pid"),
        ("ActiveState=active\nMainPID=0\n", "active_node_missing_pid"),
    ):
        with pytest.raises(NodeSupervisorError, match=error):

            def show(
                arguments: tuple[str, ...],
                timeout: float,
                output: str = output,
            ) -> CompletedProcess[str]:
                return CompletedProcess(arguments, 0, output, "")

            SystemdNodeProcessController(
                systemctl=Path("/usr/bin/systemctl"),
                run=show,
                proc_root=tmp_path,
            ).execute(NodeRuntimeAction.OBSERVE, runtime_spec())


def test_direct_contract_adapter_starts_restarts_and_stops_only_one_node(
    tmp_path: Path,
) -> None:
    binary = tmp_path / "mediamtx-test"
    binary.write_text("#!/bin/sh\nexec /bin/sleep 30\n", encoding="utf-8")
    binary.chmod(0o755)
    config_root = tmp_path / "nodes"
    config_root.mkdir(mode=0o700)
    spec = runtime_spec()
    SecureNodeConfigStore(root=config_root).install(
        spec,
        MediaNodeConfigRenderer().render(spec, management_credentials()),
        credentials=management_credentials(),
    )
    observed_pids: list[int] = []

    def identity(proc_root: Path, pid: int) -> NodeProcessSnapshot:
        observed_pids.append(pid)
        return NodeProcessSnapshot(
            active=True,
            pid=pid,
            process_start_ticks=pid + 100,
            boot_id=UUID("10000000-0000-0000-0000-000000000001"),
            executable_sha256="a" * 64,
        )

    controller = DirectNodeProcessController(
        mediamtx_binary=binary,
        config_root=config_root,
        process_identity=identity,
    )
    try:
        started = controller.execute(NodeRuntimeAction.START, spec)
        restarted = controller.execute(NodeRuntimeAction.RESTART, spec)
        stopped = controller.execute(NodeRuntimeAction.STOP, spec)
    finally:
        controller.close()

    assert started.active is True
    assert restarted.active is True
    assert started.pid != restarted.pid
    assert observed_pids == [started.pid, restarted.pid]
    assert stopped.active is False


class SmokeHttpHandler(http.server.BaseHTTPRequestHandler):
    global_config: ClassVar[dict[str, object]] = {}

    def do_GET(self) -> None:
        if self.path == "/v3/config/global/get":
            payload = json.dumps(self.global_config).encode()
        elif self.path == "/metrics":
            payload = b"metrics"
        else:
            self.send_error(404)
            return
        self.send_response(200)
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def log_message(self, format: str, *args: object) -> None:
        pass


def test_smoke_probe_checks_api_metrics_and_plain_rtsp_tcp() -> None:
    api = http.server.ThreadingHTTPServer(("127.0.0.1", 0), SmokeHttpHandler)
    metrics = http.server.ThreadingHTTPServer(("127.0.0.1", 0), SmokeHttpHandler)
    rtsp = socket.socket()
    rtsp.bind(("127.0.0.1", 0))
    rtsp.listen(1)
    api_port = int(api.server_address[1])
    metrics_port = int(metrics.server_address[1])
    rtsp_port = int(rtsp.getsockname()[1])
    spec = NodeRuntimeSpec(
        node_id=runtime_spec().node_id,
        external_port=rtsp_port,
        api_port=api_port,
        metrics_port=metrics_port,
        desired_revision=1,
        release_id="release-2026.08.12",
        mediamtx_binary_sha256="a" * 64,
    )
    SmokeHttpHandler.global_config = {
        "api": True,
        "apiAddress": f"127.0.0.1:{api_port}",
        "metrics": True,
        "metricsAddress": f"127.0.0.1:{metrics_port}",
        "rtsp": True,
        "rtspAddress": f":{rtsp_port}",
        "rtspTransports": ["tcp"],
        "rtspEncryption": "no",
        "rtmp": False,
        "hls": False,
        "webrtc": False,
        "srt": False,
    }

    def answer_rtsp() -> None:
        connection, _ = rtsp.accept()
        with connection:
            request = connection.recv(8192)
            assert request.startswith(b"OPTIONS rtsp://")
            assert b"RTSP/1.0" in request
            connection.sendall(b"RTSP/1.0 200 OK\r\nCSeq: 1\r\n\r\n")

    threads = (
        Thread(target=api.serve_forever),
        Thread(target=metrics.serve_forever),
        Thread(target=answer_rtsp),
    )
    for thread in threads:
        thread.start()
    try:
        MediaNodeSmokeProbe(timeout_seconds=1).check(spec, management_credentials())
    finally:
        api.shutdown()
        metrics.shutdown()
        api.server_close()
        metrics.server_close()
        rtsp.close()
        for thread in threads:
            thread.join(timeout=1)


def test_control_plane_uses_one_bounded_unix_request_for_an_exact_node() -> None:
    temporary = tempfile.TemporaryDirectory(prefix="rtsp-node-", dir="/tmp")
    socket_path = Path(temporary.name) / "runtime.sock"
    listener = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    listener.bind(str(socket_path))
    listener.listen(1)
    captured: dict[str, object] = {}

    def answer() -> None:
        connection, _ = listener.accept()
        with connection:
            request = connection.makefile("rb").readline(65537)
            captured.update(json.loads(request))
            connection.sendall(
                (
                    json.dumps(
                        {
                            "schema_version": 1,
                            "ok": True,
                            "observation": {
                                "state": "running",
                                "health": "healthy",
                                "management_fresh": True,
                                "config_compatible": True,
                                "applied_revision": 3,
                                "process_id": 1234,
                                "process_start_ticks": 5678,
                                "process_boot_id": "10000000-0000-0000-0000-000000000001",
                                "config_sha256": "b" * 64,
                                "release_id": "release-2026.08.12",
                            },
                            "error": None,
                        },
                        separators=(",", ":"),
                    )
                    + "\n"
                ).encode()
            )

    server = Thread(target=answer)
    server.start()
    node = MediaNode(
        id=runtime_spec().node_id,
        name="media-a",
        external_port=runtime_spec().external_port,
        api_port=runtime_spec().api_port,
        metrics_port=runtime_spec().metrics_port,
        release_id=runtime_spec().release_id,
        mediamtx_binary_sha256=runtime_spec().mediamtx_binary_sha256,
        desired_revision=3,
    )

    observation = UnixNodeRuntimeClient(
        socket_path=socket_path,
        timeout_seconds=1,
    ).execute(NodeRuntimeAction.PROVISION_START, node)

    server.join(timeout=1)
    listener.close()
    temporary.cleanup()
    assert captured["schema_version"] == 1
    assert captured["action"] == "provision_start"
    assert captured["spec"] == {
        "node_id": str(node.id),
        "external_port": 12001,
        "api_port": 13001,
        "metrics_port": 14001,
        "desired_revision": 3,
        "release_id": "release-2026.08.12",
        "mediamtx_binary_sha256": "a" * 64,
    }
    assert captured["config"] is None
    assert observation.state is NodeState.RUNNING
    assert observation.process_id == 1234


def test_runtime_client_rejects_oversized_or_malformed_helper_responses() -> None:
    temporary = tempfile.TemporaryDirectory(prefix="rtsp-node-", dir="/tmp")
    socket_path = Path(temporary.name) / "runtime.sock"
    listener = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    listener.bind(str(socket_path))
    listener.listen(1)

    def answer() -> None:
        connection, _ = listener.accept()
        with connection:
            connection.makefile("rb").readline(65537)
            connection.sendall(b'{"ok":true,"unexpected":"field"}\n')

    server = Thread(target=answer)
    server.start()
    node = MediaNode(
        id=runtime_spec().node_id,
        name="media-a",
        external_port=runtime_spec().external_port,
        api_port=runtime_spec().api_port,
        metrics_port=runtime_spec().metrics_port,
        release_id=runtime_spec().release_id,
        mediamtx_binary_sha256=runtime_spec().mediamtx_binary_sha256,
        desired_revision=3,
    )

    with pytest.raises(RuntimeError, match="node_runtime_response_invalid"):
        UnixNodeRuntimeClient(socket_path=socket_path, timeout_seconds=1).execute(
            NodeRuntimeAction.OBSERVE,
            node,
        )

    server.join(timeout=1)
    listener.close()
    temporary.cleanup()


def test_runtime_client_reports_missing_socket_without_exposing_os_error(
    tmp_path: Path,
) -> None:
    node = MediaNode(
        id=runtime_spec().node_id,
        name="media-a",
        external_port=runtime_spec().external_port,
        api_port=runtime_spec().api_port,
        metrics_port=runtime_spec().metrics_port,
        release_id=runtime_spec().release_id,
        mediamtx_binary_sha256=runtime_spec().mediamtx_binary_sha256,
        desired_revision=3,
    )

    with pytest.raises(NodeSupervisorError, match="node_runtime_unavailable"):
        UnixNodeRuntimeClient(
            socket_path=tmp_path / "missing.sock",
            timeout_seconds=0.1,
        ).execute(NodeRuntimeAction.OBSERVE, node)


def test_root_helper_rejects_a_port_outside_its_allowlist_before_process_mutation(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes"
    root.mkdir(mode=0o700)
    process = RecordingProcessController()
    server = UnixNodeSupervisorServer(
        supervisor=LinuxNodeSupervisor(
            config_store=SecureNodeConfigStore(root=root),
            process=process,
            smoke=HealthySmokeProbe(),
            port_is_bindable=lambda port: False,
        ),
        policy=NodeRuntimePolicy(
            external_port_start=12500,
            external_port_end=12599,
            api_port_start=13000,
            api_port_end=13099,
            metrics_port_start=14000,
            metrics_port_end=14099,
            release_id="release-2026.08.12",
            mediamtx_binary_sha256="a" * 64,
        ),
    )
    client_socket, server_socket = socket.socketpair()
    request = {
        "schema_version": 1,
        "action": "provision_start",
        "spec": {
            "node_id": str(runtime_spec().node_id),
            "external_port": runtime_spec().external_port,
            "api_port": runtime_spec().api_port,
            "metrics_port": runtime_spec().metrics_port,
            "desired_revision": 3,
            "release_id": runtime_spec().release_id,
            "mediamtx_binary_sha256": "a" * 64,
        },
        "config": None,
    }
    client_socket.sendall((json.dumps(request) + "\n").encode())

    server.serve_connection(server_socket)

    response = json.loads(client_socket.makefile("rb").readline())
    client_socket.close()
    server_socket.close()
    assert response == {
        "schema_version": 1,
        "ok": False,
        "observation": None,
        "error": "node_external_port_not_allowed",
    }
    assert process.commands == []


def test_root_helper_executes_a_valid_request_and_returns_bound_observation(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes-valid"
    root.mkdir(mode=0o700)
    process = RecordingProcessController()
    server = UnixNodeSupervisorServer(
        supervisor=LinuxNodeSupervisor(
            config_store=SecureNodeConfigStore(root=root),
            process=process,
            smoke=HealthySmokeProbe(),
            port_is_bindable=lambda port: False,
        ),
        policy=NodeRuntimePolicy(
            external_port_start=12000,
            external_port_end=12099,
            api_port_start=13000,
            api_port_end=13099,
            metrics_port_start=14000,
            metrics_port_end=14099,
            release_id="release-2026.08.12",
            mediamtx_binary_sha256="a" * 64,
        ),
    )
    client_socket, server_socket = socket.socketpair()
    request = {
        "schema_version": 1,
        "action": "provision_start",
        "spec": {
            "node_id": str(runtime_spec().node_id),
            "external_port": runtime_spec().external_port,
            "api_port": runtime_spec().api_port,
            "metrics_port": runtime_spec().metrics_port,
            "desired_revision": runtime_spec().desired_revision,
            "release_id": runtime_spec().release_id,
            "mediamtx_binary_sha256": runtime_spec().mediamtx_binary_sha256,
        },
        "config": None,
    }
    client_socket.sendall((json.dumps(request) + "\n").encode())

    server.serve_connection(server_socket)

    response = json.loads(client_socket.makefile("rb").readline())
    client_socket.close()
    server_socket.close()
    assert response["ok"] is True
    assert response["error"] is None
    assert response["observation"]["state"] == "running"
    assert response["observation"]["process_id"] == 1234


def test_root_helper_ignores_a_disconnected_response_peer(tmp_path: Path) -> None:
    root = tmp_path / "nodes-disconnect"
    root.mkdir(mode=0o700)
    server = UnixNodeSupervisorServer(
        supervisor=LinuxNodeSupervisor(
            config_store=SecureNodeConfigStore(root=root),
            process=RecordingProcessController(),
            smoke=HealthySmokeProbe(),
            port_is_bindable=lambda port: False,
        ),
        policy=NodeRuntimePolicy(
            external_port_start=12000,
            external_port_end=12099,
            api_port_start=13000,
            api_port_end=13099,
            metrics_port_start=14000,
            metrics_port_end=14099,
            release_id="release-2026.08.12",
            mediamtx_binary_sha256="a" * 64,
        ),
    )
    client_socket, server_socket = socket.socketpair()
    client_socket.sendall(b"invalid\n")
    client_socket.close()

    server.serve_connection(server_socket)

    server_socket.close()


def test_root_helper_runs_colliding_node_ids_independently(tmp_path: Path) -> None:
    root = tmp_path / "nodes-independent-locks"
    root.mkdir(mode=0o700)
    first_entered = Event()
    release_first = Event()
    second_entered = Event()

    first_id = UUID(int=1)
    second_id = UUID(int=5)  # collided with the old four-stripe implementation.

    class BlockingSupervisor(LinuxNodeSupervisor):
        def execute(
            self,
            command: NodeRuntimeCommand,
            *,
            deadline: NodeOperationDeadline | None = None,
            cleanup_reserve_seconds: float = 3,
        ) -> NodeRuntimeObservation:
            if command.spec.node_id == first_id:
                first_entered.set()
                assert release_first.wait(timeout=5)
            else:
                second_entered.set()
            return NodeRuntimeObservation(
                state=NodeState.STOPPED,
                health=NodeHealth.UNKNOWN,
                config_compatible=False,
            )

    server = UnixNodeSupervisorServer(
        supervisor=BlockingSupervisor(
            config_store=SecureNodeConfigStore(root=root),
            process=RecordingProcessController(),
            smoke=HealthySmokeProbe(),
            port_is_bindable=lambda port: True,
        ),
        policy=NodeRuntimePolicy(
            external_port_start=12000,
            external_port_end=12100,
            api_port_start=13000,
            api_port_end=13100,
            metrics_port_start=14000,
            metrics_port_end=14100,
            release_id="release-2026.08.12",
            mediamtx_binary_sha256="a" * 64,
        ),
        max_workers=1,
    )

    def request(node_id: UUID, offset: int) -> dict[str, object]:
        client, connection = socket.socketpair()
        client.sendall(
            (
                json.dumps(
                    {
                        "schema_version": 1,
                        "action": "observe",
                        "spec": {
                            "node_id": str(node_id),
                            "external_port": 12000 + offset,
                            "api_port": 13000 + offset,
                            "metrics_port": 14000 + offset,
                            "desired_revision": 1,
                            "release_id": "release-2026.08.12",
                            "mediamtx_binary_sha256": "a" * 64,
                        },
                        "config": None,
                    }
                )
                + "\n"
            ).encode()
        )
        server.serve_connection(connection)
        response = cast(dict[str, object], json.loads(client.makefile("rb").readline()))
        client.close()
        connection.close()
        return response

    with ThreadPoolExecutor(max_workers=2) as executor:
        first = executor.submit(request, first_id, 1)
        assert first_entered.wait(timeout=1)
        second = executor.submit(request, second_id, 2)
        assert second_entered.wait(timeout=1)
        release_first.set()
        assert isinstance(first.result(timeout=1)["ok"], bool)
        assert isinstance(second.result(timeout=1)["ok"], bool)



def test_root_helper_deadline_times_out_start_and_uses_reserved_cleanup(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes-deadline"
    root.mkdir(mode=0o700)
    observed_deadlines: list[object | None] = []

    class DeadlineProcess(RecordingProcessController):
        def execute(
            self,
            action: NodeRuntimeAction,
            spec: NodeRuntimeSpec,
            deadline: object | None = None,
        ) -> NodeProcessSnapshot:
            observed_deadlines.append(deadline)
            if action is NodeRuntimeAction.PROVISION_START:
                raise NodeSupervisorError("node_runtime_operation_timeout")
            return super().execute(action, spec, deadline)

    process = DeadlineProcess()
    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root),
        process=process,
        smoke=HealthySmokeProbe(),
        port_is_bindable=lambda port: True,
    )
    deadline = NodeOperationDeadline(expires_monotonic=time.monotonic() + 1)

    with pytest.raises(NodeSupervisorError, match="node_runtime_operation_timeout"):
        supervisor.execute(
            NodeRuntimeCommand.for_node(NodeRuntimeAction.PROVISION_START, runtime_spec()),
            deadline=deadline,
            cleanup_reserve_seconds=0.2,
        )

    assert process.commands == [(NodeRuntimeAction.STOP, runtime_spec().node_id)]
    assert observed_deadlines[0] != observed_deadlines[1]


def test_expired_start_deadline_cannot_mutate_node_configuration(tmp_path: Path) -> None:
    root = tmp_path / "nodes-expired-before-mutation"
    root.mkdir(mode=0o700)
    process = RecordingProcessController()
    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root),
        process=process,
        smoke=HealthySmokeProbe(),
        port_is_bindable=lambda port: True,
    )

    with pytest.raises(NodeSupervisorError, match="node_runtime_operation_timeout"):
        supervisor.execute(
            NodeRuntimeCommand.for_node(
                NodeRuntimeAction.PROVISION_START,
                runtime_spec(),
            ),
            deadline=NodeOperationDeadline(
                expires_monotonic=0,
                monotonic=lambda: 1,
            ),
            cleanup_reserve_seconds=0.2,
        )

    assert tuple(root.iterdir()) == ()
    assert process.commands == []


def test_root_helper_times_out_a_partial_request_without_blocking_forever(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes-timeout"
    root.mkdir(mode=0o700)
    server = UnixNodeSupervisorServer(
        supervisor=LinuxNodeSupervisor(
            config_store=SecureNodeConfigStore(root=root),
            process=RecordingProcessController(),
            smoke=HealthySmokeProbe(),
            port_is_bindable=lambda port: True,
        ),
        policy=NodeRuntimePolicy(
            external_port_start=12000,
            external_port_end=12099,
            api_port_start=13000,
            api_port_end=13099,
            metrics_port_start=14000,
            metrics_port_end=14099,
            release_id="release-2026.08.12",
            mediamtx_binary_sha256="a" * 64,
        ),
        request_timeout_seconds=0.05,
    )
    client_socket, server_socket = socket.socketpair()
    client_socket.settimeout(1)
    client_socket.sendall(b'{"schema_version":')

    started = time.monotonic()
    server.serve_connection(server_socket)
    elapsed = time.monotonic() - started

    response = json.loads(client_socket.makefile("rb").readline())
    client_socket.close()
    server_socket.close()
    assert elapsed < 0.5
    assert response["ok"] is False
    assert response["error"] == "node_runtime_request_timeout"


@pytest.mark.parametrize(
    ("changes", "error"),
    (
        ({"external_port": 11999}, "node_external_port_not_allowed"),
        ({"api_port": 12999}, "node_api_port_not_allowed"),
        ({"metrics_port": 13999}, "node_metrics_port_not_allowed"),
        ({"release_id": "wrong"}, "node_release_not_allowed"),
    ),
)
def test_root_helper_policy_rejects_every_out_of_contract_dimension(
    changes: dict[str, object],
    error: str,
) -> None:
    policy = NodeRuntimePolicy(
        external_port_start=12000,
        external_port_end=12099,
        api_port_start=13000,
        api_port_end=13099,
        metrics_port_start=14000,
        metrics_port_end=14099,
        release_id="release-2026.08.12",
        mediamtx_binary_sha256="a" * 64,
    )
    values: dict[str, object] = {
        "node_id": runtime_spec().node_id,
        "external_port": 12001,
        "api_port": 13001,
        "metrics_port": 14001,
        "desired_revision": 3,
        "release_id": "release-2026.08.12",
        "mediamtx_binary_sha256": "a" * 64,
    }
    values.update(changes)

    with pytest.raises(NodeSupervisorError, match=error):
        policy.validate(NodeRuntimeSpec(**values))  # type: ignore[arg-type]


def test_helper_settings_reject_overlap_and_non_absolute_privileged_paths() -> None:
    with pytest.raises(ValueError, match="node_helper_port_ranges_overlap"):
        helper_settings(api_port_start=12099)
    with pytest.raises(ValueError, match="node_helper_path_invalid"):
        helper_settings(config_root=Path("relative"))

    settings = helper_settings()
    assert settings.policy().release_id == "release-2026.08.12"


def test_helper_policy_allows_current_and_previous_verified_releases() -> None:
    settings = helper_settings(
        previous_release_id="release-2026.08.11",
        previous_mediamtx_binary=Path(
            "/opt/rtsp-proxy/releases/release-2026.08.11/bin/mediamtx"
        ),
        previous_mediamtx_binary_sha256="b" * 64,
    )
    previous = NodeRuntimeSpec(
        node_id=runtime_spec().node_id,
        external_port=runtime_spec().external_port,
        api_port=runtime_spec().api_port,
        metrics_port=runtime_spec().metrics_port,
        desired_revision=3,
        release_id="release-2026.08.11",
        mediamtx_binary_sha256="b" * 64,
    )

    settings.policy().validate(previous)

    with pytest.raises(NodeSupervisorError, match="node_release_not_allowed"):
        settings.policy().validate(
            NodeRuntimeSpec(
                node_id=previous.node_id,
                external_port=previous.external_port,
                api_port=previous.api_port,
                metrics_port=previous.metrics_port,
                desired_revision=previous.desired_revision,
                release_id="release-unknown",
                mediamtx_binary_sha256="c" * 64,
            )
        )


def test_secure_store_selects_the_binary_from_the_verified_release_catalog(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes-catalog"
    root.mkdir(mode=0o700)
    current = tmp_path / "release-current" / "mediamtx"
    previous = tmp_path / "release-previous" / "mediamtx"
    current.parent.mkdir()
    previous.parent.mkdir()
    current.write_bytes(b"current")
    previous.write_bytes(b"previous")
    previous_digest = hashlib.sha256(b"previous").hexdigest()
    spec = NodeRuntimeSpec(
        node_id=runtime_spec().node_id,
        external_port=12001,
        api_port=13001,
        metrics_port=14001,
        desired_revision=1,
        release_id="release-previous",
        mediamtx_binary_sha256=previous_digest,
    )
    store = SecureNodeConfigStore(
        root=root,
        binary_catalog={
            ("release-current", hashlib.sha256(b"current").hexdigest()): current,
            ("release-previous", previous_digest): previous,
        },
    )

    store.provision(spec)

    assert (root / str(spec.node_id) / "runtime.env").read_text() == (
        f"RTSP_PROXY_MEDIAMTX_BINARY={previous}\n"
    )


def test_helper_settings_require_a_complete_distinct_previous_release() -> None:
    with pytest.raises(ValueError, match="node_helper_previous_release_incomplete"):
        helper_settings(previous_release_id="release-2026.08.11")
    with pytest.raises(ValueError, match="node_helper_previous_release_duplicate"):
        helper_settings(
            previous_release_id="release-2026.08.12",
            previous_mediamtx_binary=Path(
                "/opt/rtsp-proxy/releases/release-2026.08.11/bin/mediamtx"
            ),
            previous_mediamtx_binary_sha256="b" * 64,
        )


def test_runtime_credentials_and_deadlines_reject_invalid_boundaries() -> None:
    with pytest.raises(ValueError, match="node_management_credentials_invalid"):
        NodeManagementCredentials(username="wrong", password="x" * 32)
    with pytest.raises(ValueError, match="node_reader_credentials_invalid"):
        NodeReaderCredentials(username="wrong", password="x" * 32)
    expired = NodeOperationDeadline(expires_monotonic=0, monotonic=lambda: 1)
    with pytest.raises(NodeSupervisorError, match="node_runtime_operation_timeout"):
        expired.remaining_seconds()
    with pytest.raises(ValueError, match="node_runtime_deadline_reserve_invalid"):
        NodeOperationDeadline(expires_monotonic=2, monotonic=lambda: 1).before(0)


def test_runtime_policy_rejects_an_incomplete_previous_release_pin() -> None:
    policy = NodeRuntimePolicy(
        external_port_start=12000,
        external_port_end=12099,
        api_port_start=13000,
        api_port_end=13099,
        metrics_port_start=14000,
        metrics_port_end=14099,
        release_id="release-2026.08.12",
        mediamtx_binary_sha256="a" * 64,
        previous_release_id="release-2026.08.11",
    )

    with pytest.raises(NodeSupervisorError, match="node_release_policy_invalid"):
        policy.validate(runtime_spec())


@pytest.mark.parametrize(
    "changes",
    (
        {"request_timeout_seconds": 0},
        {"operation_timeout_seconds": 56},
        {"cleanup_reserve_seconds": 19},
        {"cleanup_reserve_seconds": 55},
        {"max_workers": 0},
    ),
)
def test_root_helper_rejects_unsafe_budget_or_worker_configuration(
    tmp_path: Path,
    changes: dict[str, object],
) -> None:
    root = tmp_path / "nodes-invalid-server"
    root.mkdir(mode=0o700)
    values: dict[str, object] = {
        "supervisor": LinuxNodeSupervisor(
            config_store=SecureNodeConfigStore(root=root),
            process=RecordingProcessController(),
            smoke=HealthySmokeProbe(),
            port_is_bindable=lambda port: True,
        ),
        "policy": NodeRuntimePolicy(
            external_port_start=12000,
            external_port_end=12099,
            api_port_start=13000,
            api_port_end=13099,
            metrics_port_start=14000,
            metrics_port_end=14099,
            release_id="release-2026.08.12",
            mediamtx_binary_sha256="a" * 64,
        ),
    }
    values.update(changes)

    with pytest.raises(ValueError):
        UnixNodeSupervisorServer(**values)  # type: ignore[arg-type]


def test_root_helper_rejects_an_expired_client_deadline(tmp_path: Path) -> None:
    root = tmp_path / "nodes-expired"
    root.mkdir(mode=0o700)
    server = UnixNodeSupervisorServer(
        supervisor=LinuxNodeSupervisor(
            config_store=SecureNodeConfigStore(root=root),
            process=RecordingProcessController(),
            smoke=HealthySmokeProbe(),
            port_is_bindable=lambda port: True,
        ),
        policy=NodeRuntimePolicy(
            external_port_start=12000,
            external_port_end=12099,
            api_port_start=13000,
            api_port_end=13099,
            metrics_port_start=14000,
            metrics_port_end=14099,
            release_id="release-2026.08.12",
            mediamtx_binary_sha256="a" * 64,
        ),
        wall_time=lambda: 2,
    )

    with pytest.raises(NodeSupervisorError, match="node_runtime_operation_timeout"):
        server._operation_deadline(1000)


def test_runtime_client_rejects_invalid_constructor_boundaries(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="node_runtime_socket_must_be_absolute"):
        UnixNodeRuntimeClient(socket_path=Path("relative.sock"), timeout_seconds=1)
    with pytest.raises(ValueError, match="node_runtime_timeout_invalid"):
        UnixNodeRuntimeClient(socket_path=tmp_path / "runtime.sock", timeout_seconds=0)


def test_root_helper_decoder_rejects_malformed_and_wrong_schema_requests() -> None:
    for request in (
        b"",
        b"{}",
        b"not-json\n",
        b'{"schema_version":2}\n',
    ):
        with pytest.raises(NodeSupervisorError, match="node_runtime_request_invalid"):
            UnixNodeSupervisorServer._decode_command(request)


def test_runtime_client_rejects_structurally_invalid_error_response() -> None:
    temporary = tempfile.TemporaryDirectory(prefix="rtsp-node-", dir="/tmp")
    socket_path = Path(temporary.name) / "runtime.sock"
    listener = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    listener.bind(str(socket_path))
    listener.listen(1)

    def answer() -> None:
        connection, _ = listener.accept()
        with connection:
            connection.makefile("rb").readline(65537)
            connection.sendall(
                b'{"schema_version":1,"ok":false,"observation":null,"error":null}\n'
            )

    server = Thread(target=answer)
    server.start()
    node = MediaNode(
        id=runtime_spec().node_id,
        name="media-a",
        external_port=12001,
        api_port=13001,
        metrics_port=14001,
        release_id=runtime_spec().release_id,
        mediamtx_binary_sha256="a" * 64,
        desired_revision=3,
    )

    with pytest.raises(NodeSupervisorError, match="node_runtime_response_invalid"):
        UnixNodeRuntimeClient(socket_path=socket_path, timeout_seconds=1).execute(
            NodeRuntimeAction.OBSERVE,
            node,
        )

    server.join(timeout=1)
    listener.close()
    temporary.cleanup()


def test_secure_store_rejects_ambiguous_or_unknown_binary_catalog(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes-ambiguous"
    root.mkdir(mode=0o700)
    binary = tmp_path / "mediamtx"
    binary.write_bytes(b"binary")
    with pytest.raises(ValueError, match="node_binary_catalog_ambiguous"):
        SecureNodeConfigStore(
            root=root,
            binary_path=binary,
            binary_catalog={("release", "a" * 64): binary},
        )
    store = SecureNodeConfigStore(
        root=root,
        binary_catalog={("another-release", "b" * 64): binary},
    )
    with pytest.raises(ValueError, match="node_release_not_allowed"):
        store.provision(runtime_spec())


def helper_settings(
    *,
    api_port_start: int = 13000,
    config_root: Path = Path("/etc/rtsp-proxy/nodes"),
    **changes: object,
) -> NodeHelperSettings:
    values: dict[str, object] = {
        "config_root": config_root,
        "mediamtx_binary": Path(
            "/opt/rtsp-proxy/releases/release-2026.08.12/bin/mediamtx"
        ),
        "external_port_start": 12000,
        "external_port_end": 12099,
        "api_port_start": api_port_start,
        "api_port_end": 13099,
        "metrics_port_start": 14000,
        "metrics_port_end": 14099,
        "release_id": "release-2026.08.12",
        "mediamtx_binary_sha256": "a" * 64,
    }
    values.update(changes)
    return NodeHelperSettings(**values)  # type: ignore[arg-type]
def test_reconfigure_preserves_credentials_and_changes_only_the_typed_config(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes"
    root.mkdir(mode=0o700)
    store = SecureNodeConfigStore(root=root)
    original = runtime_spec()
    store.install(
        original,
        MediaNodeConfigRenderer().render(
            original,
            management_credentials(),
            reader_credentials(),
        ),
        credentials=management_credentials(),
        reader_credentials=reader_credentials(),
    )
    changed = NodeRuntimeSpec(
        node_id=original.node_id,
        external_port=12099,
        api_port=original.api_port,
        metrics_port=original.metrics_port,
        desired_revision=original.desired_revision + 1,
        release_id=original.release_id,
        mediamtx_binary_sha256=original.mediamtx_binary_sha256,
    )

    rendered = store.reconfigure(changed)

    assert "rtspAddress: :12099" in rendered.content
    assert store.credentials(changed) == management_credentials()
    assert store.reader_credentials(changed) == reader_credentials()
    assert store.digest(changed) == rendered.sha256


def test_secure_delete_refuses_foreign_files_and_removes_only_owned_node_config(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes"
    root.mkdir(mode=0o700)
    store = SecureNodeConfigStore(root=root)
    spec = runtime_spec()
    store.install(
        spec,
        MediaNodeConfigRenderer().render(
            spec,
            management_credentials(),
            reader_credentials(),
        ),
        credentials=management_credentials(),
        reader_credentials=reader_credentials(),
    )
    node_dir = root / str(spec.node_id)
    foreign = node_dir / "foreign"
    foreign.write_text("do not delete", encoding="utf-8")
    foreign.chmod(0o600)

    with pytest.raises(ValueError, match="node_config_directory_not_owned"):
        store.delete(spec)

    assert foreign.read_text(encoding="utf-8") == "do not delete"
    foreign.unlink()
    store.delete(spec)
    assert not node_dir.exists()


def test_reconfigure_requires_both_existing_credential_sets(tmp_path: Path) -> None:
    root = tmp_path / "nodes-missing-credentials"
    root.mkdir(mode=0o700)
    spec = runtime_spec()
    node_dir = root / str(spec.node_id)
    node_dir.mkdir(mode=0o700)
    (node_dir / "management.json").write_text(
        json.dumps(
            {
                "password": management_credentials().password,
                "username": management_credentials().username,
            },
            separators=(",", ":"),
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    (node_dir / "management.json").chmod(0o600)

    with pytest.raises(ValueError, match="node_credentials_missing"):
        SecureNodeConfigStore(root=root).reconfigure(spec)


def test_secure_delete_is_idempotent_and_rejects_unsafe_owned_file(tmp_path: Path) -> None:
    root = tmp_path / "nodes-delete-safety"
    root.mkdir(mode=0o700)
    store = SecureNodeConfigStore(root=root)
    spec = runtime_spec()

    store.delete(spec)
    node_dir = root / str(spec.node_id)
    node_dir.mkdir(mode=0o700)
    private_file = node_dir / "mediamtx.yml"
    private_file.write_text("owned", encoding="utf-8")
    private_file.chmod(0o644)

    with pytest.raises(ValueError, match="node_private_file_unsafe"):
        store.delete(spec)

    assert private_file.exists()

    missing = root / str(UUID("00000000-0000-0000-0000-000000000002"))
    missing.symlink_to(root / "does-not-exist")
    with pytest.raises(ValueError):
        store.delete(
            NodeRuntimeSpec(
                node_id=UUID("00000000-0000-0000-0000-000000000002"),
                external_port=12002,
                api_port=13002,
                metrics_port=14002,
                desired_revision=1,
                release_id=spec.release_id,
                mediamtx_binary_sha256=spec.mediamtx_binary_sha256,
            )
        )


def test_supervisor_reconfigures_with_existing_credentials_before_restart(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes-reconfigure"
    root.mkdir(mode=0o700)
    original = runtime_spec()
    store = SecureNodeConfigStore(root=root)
    store.install(
        original,
        MediaNodeConfigRenderer().render(
            original,
            management_credentials(),
            reader_credentials(),
        ),
        credentials=management_credentials(),
        reader_credentials=reader_credentials(),
    )
    changed = NodeRuntimeSpec(
        node_id=original.node_id,
        external_port=12099,
        api_port=original.api_port,
        metrics_port=original.metrics_port,
        desired_revision=original.desired_revision + 1,
        release_id=original.release_id,
        mediamtx_binary_sha256=original.mediamtx_binary_sha256,
    )
    process = RecordingProcessController()

    class ChangedSmoke:
        def check(
            self,
            spec: NodeRuntimeSpec,
            credentials: NodeManagementCredentials,
            deadline: object | None = None,
        ) -> None:
            assert spec == changed
            assert credentials == management_credentials()

    observation = LinuxNodeSupervisor(
        config_store=store,
        process=process,
        smoke=ChangedSmoke(),
        port_is_bindable=lambda port: False,
    ).execute(NodeRuntimeCommand.for_node(NodeRuntimeAction.RECONFIGURE_RESTART, changed))

    assert observation.applied_revision == changed.desired_revision
    assert "rtspAddress: :12099" in (root / str(changed.node_id) / "mediamtx.yml").read_text(
        encoding="utf-8"
    )
    assert process.commands == [
        (NodeRuntimeAction.RECONFIGURE_RESTART, changed.node_id),
        (NodeRuntimeAction.OBSERVE, changed.node_id),
    ]


def test_supervisor_delete_stops_and_removes_only_exact_node_config(tmp_path: Path) -> None:
    root = tmp_path / "nodes-delete"
    root.mkdir(mode=0o700)
    spec = runtime_spec()
    store = SecureNodeConfigStore(root=root)
    store.install(
        spec,
        MediaNodeConfigRenderer().render(
            spec,
            management_credentials(),
            reader_credentials(),
        ),
        credentials=management_credentials(),
        reader_credentials=reader_credentials(),
    )
    process = RecordingProcessController()

    observation = LinuxNodeSupervisor(
        config_store=store,
        process=process,
        smoke=HealthySmokeProbe(),
        port_is_bindable=lambda port: True,
    ).execute(NodeRuntimeCommand.for_node(NodeRuntimeAction.DELETE, spec))

    assert observation.state is NodeState.STOPPED
    assert not (root / str(spec.node_id)).exists()
    assert process.commands == [(NodeRuntimeAction.DELETE, spec.node_id)]
