from __future__ import annotations

import hashlib
import http.server
import json
import socket
import tempfile
from pathlib import Path
from subprocess import CompletedProcess
from threading import Thread
from typing import ClassVar
from uuid import UUID

import pytest

from rtsp_proxy.node_runtime import (
    DirectNodeProcessController,
    LinuxNodeSupervisor,
    MediaNodeConfigRenderer,
    MediaNodeSmokeProbe,
    NodeHelperSettings,
    NodeProcessSnapshot,
    NodeRuntimeCommand,
    NodeRuntimePolicy,
    NodeRuntimeSpec,
    NodeSupervisorError,
    RenderedNodeConfig,
    SecureNodeConfigStore,
    SystemdNodeProcessController,
    UnixNodeRuntimeClient,
    UnixNodeSupervisorServer,
)
from rtsp_proxy.nodes import MediaNode, NodeHealth, NodeRuntimeAction, NodeState


def runtime_spec(*, node_suffix: int = 1) -> NodeRuntimeSpec:
    return NodeRuntimeSpec(
        node_id=UUID(f"00000000-0000-0000-0000-{node_suffix:012d}"),
        external_port=12000 + node_suffix,
        api_port=13000 + node_suffix,
        metrics_port=14000 + node_suffix,
        desired_revision=3,
        release_id="release-2026.08.12",
        mediamtx_binary_sha256="a" * 64,
    )


def test_renderer_produces_one_loopback_managed_ordinary_rtsp_tcp_node() -> None:
    rendered = MediaNodeConfigRenderer().render(runtime_spec())

    assert rendered.sha256 == (
        "1b1273893a3156d5148b36e29cbfe8b63f6bf070caf331f02c18542519b87965"
    )
    assert rendered.content == (
        "# Generated by rtsp-proxy. Do not edit.\n"
        "logLevel: info\n"
        "logDestinations: [stdout]\n"
        "logStructured: true\n"
        "authMethod: internal\n"
        "authInternalUsers:\n"
        "  - user: any\n"
        "    pass:\n"
        '    ips: [\"127.0.0.1\", \"::1\"]\n'
        "    permissions:\n"
        "      - action: api\n"
        "      - action: metrics\n"
        "api: true\n"
        "apiAddress: 127.0.0.1:13001\n"
        "apiEncryption: false\n"
        "apiAllowOrigins: []\n"
        "apiTrustedProxies: []\n"
        "metrics: true\n"
        "metricsAddress: 127.0.0.1:14001\n"
        "metricsEncryption: false\n"
        "metricsAllowOrigins: []\n"
        "metricsTrustedProxies: []\n"
        "pprof: false\n"
        "playback: false\n"
        "rtsp: true\n"
        "rtspTransports: [tcp]\n"
        'rtspEncryption: "no"\n'
        "rtspAddress: :12001\n"
        "rtspAuthMethods: [basic]\n"
        "rtspTrustedProxies: []\n"
        "rtmp: false\n"
        "hls: false\n"
        "webrtc: false\n"
        "srt: false\n"
        "moq: false\n"
        "paths: {}\n"
    )
    assert "rtsps" not in rendered.content.lower()
    assert "udp" not in rendered.content.lower()


def test_runtime_command_is_closed_over_an_exact_node_spec() -> None:
    spec = runtime_spec()

    command = NodeRuntimeCommand.for_node(NodeRuntimeAction.PROVISION_START, spec)

    assert command.action is NodeRuntimeAction.PROVISION_START
    assert command.spec == spec
    assert command.config is not None
    assert command.config.sha256 == MediaNodeConfigRenderer().render(spec).sha256


def test_non_provisioning_commands_cannot_smuggle_a_config() -> None:
    spec = runtime_spec()
    rendered = MediaNodeConfigRenderer().render(spec)

    with pytest.raises(ValueError, match="runtime_config_not_allowed"):
        NodeRuntimeCommand(
            action=NodeRuntimeAction.RESTART,
            spec=spec,
            config=rendered,
        )


def test_secure_config_store_atomically_installs_exact_node_file(tmp_path: Path) -> None:
    root = tmp_path / "nodes"
    root.mkdir(mode=0o750)
    spec = runtime_spec()
    rendered = MediaNodeConfigRenderer().render(spec)
    store = SecureNodeConfigStore(root=root, group_id=None)

    installed = store.install(spec, rendered)

    assert installed == root / str(spec.node_id) / "mediamtx.yml"
    assert installed.read_text(encoding="utf-8") == rendered.content
    assert installed.stat().st_mode & 0o777 == 0o640
    assert installed.parent.stat().st_mode & 0o777 == 0o750
    assert tuple(root.rglob("*.tmp")) == ()


def test_secure_config_store_refuses_a_symlinked_node_directory(tmp_path: Path) -> None:
    root = tmp_path / "nodes"
    root.mkdir(mode=0o750)
    escaped = tmp_path / "escaped"
    escaped.mkdir()
    spec = runtime_spec()
    (root / str(spec.node_id)).symlink_to(escaped, target_is_directory=True)

    with pytest.raises(ValueError, match="node_config_directory_unsafe"):
        SecureNodeConfigStore(root=root, group_id=None).install(
            spec,
            MediaNodeConfigRenderer().render(spec),
        )

    assert tuple(escaped.iterdir()) == ()


def test_runtime_spec_rejects_overlapping_or_non_loopback_management_ports() -> None:
    with pytest.raises(ValueError, match="node_ports_not_unique"):
        NodeRuntimeSpec(
            node_id=UUID("00000000-0000-0000-0000-000000000001"),
            external_port=12000,
            api_port=12000,
            metrics_port=14000,
            desired_revision=1,
            release_id="release-1",
            mediamtx_binary_sha256="a" * 64,
        )


@pytest.mark.parametrize(
    ("changes", "error"),
    (
        ({"external_port": 0}, "node_port_invalid"),
        ({"desired_revision": 0}, "node_desired_revision_invalid"),
        ({"release_id": ""}, "node_release_id_invalid"),
        ({"mediamtx_binary_sha256": "A" * 64}, "node_binary_sha256_invalid"),
    ),
)
def test_runtime_spec_rejects_noncanonical_identity(
    changes: dict[str, object],
    error: str,
) -> None:
    values: dict[str, object] = {
        "node_id": runtime_spec().node_id,
        "external_port": 12001,
        "api_port": 13001,
        "metrics_port": 14001,
        "desired_revision": 1,
        "release_id": "release-1",
        "mediamtx_binary_sha256": "a" * 64,
    }
    values.update(changes)

    with pytest.raises(ValueError, match=error):
        NodeRuntimeSpec(**values)  # type: ignore[arg-type]


def test_rendered_config_requires_a_final_newline_and_matching_digest() -> None:
    with pytest.raises(ValueError, match="node_config_final_newline_required"):
        RenderedNodeConfig.from_content("paths: {}")

    with pytest.raises(ValueError, match="node_config_digest_mismatch"):
        root = Path(tempfile.mkdtemp(prefix="rtsp-node-", dir="/tmp"))
        try:
            root.chmod(0o750)
            SecureNodeConfigStore(root=root, group_id=None).install(
                runtime_spec(),
                RenderedNodeConfig(content="paths: {}\n", sha256="0" * 64),
            )
        finally:
            root.rmdir()


def test_runtime_command_requires_config_only_for_provisioning() -> None:
    with pytest.raises(ValueError, match="runtime_config_required"):
        NodeRuntimeCommand(
            action=NodeRuntimeAction.PROVISION_START,
            spec=runtime_spec(),
        )


def test_process_snapshot_rejects_partial_or_stale_identity() -> None:
    with pytest.raises(ValueError, match="active_node_process_identity_incomplete"):
        NodeProcessSnapshot(
            active=True,
            pid=1,
            process_start_ticks=None,
            boot_id=None,
            executable_sha256=None,
        )
    with pytest.raises(ValueError, match="inactive_node_process_has_identity"):
        NodeProcessSnapshot(
            active=False,
            pid=1,
            process_start_ticks=None,
            boot_id=None,
            executable_sha256=None,
        )


def test_secure_store_rejects_relative_or_writable_roots_and_wrong_node_mode(
    tmp_path: Path,
) -> None:
    with pytest.raises(ValueError, match="node_config_root_must_be_absolute"):
        SecureNodeConfigStore(root=Path("relative"), group_id=None)

    writable = tmp_path / "writable"
    writable.mkdir(mode=0o777)
    writable.chmod(0o777)
    with pytest.raises(ValueError, match="node_config_root_unsafe"):
        SecureNodeConfigStore(root=writable, group_id=None).install(
            runtime_spec(),
            MediaNodeConfigRenderer().render(runtime_spec()),
        )

    root = tmp_path / "nodes-unsafe"
    root.mkdir(mode=0o750)
    node = root / str(runtime_spec().node_id)
    node.mkdir(mode=0o700)
    with pytest.raises(ValueError, match="node_config_directory_unsafe"):
        SecureNodeConfigStore(root=root, group_id=None).install(
            runtime_spec(),
            MediaNodeConfigRenderer().render(runtime_spec()),
        )


class HealthySmokeProbe:
    def check(self, spec: NodeRuntimeSpec) -> None:
        assert spec == runtime_spec()


class RecordingProcessController:
    def __init__(self) -> None:
        self.commands: list[tuple[NodeRuntimeAction, UUID]] = []

    def execute(
        self,
        action: NodeRuntimeAction,
        spec: NodeRuntimeSpec,
    ) -> NodeProcessSnapshot:
        self.commands.append((action, spec.node_id))
        return NodeProcessSnapshot(
            active=action is not NodeRuntimeAction.STOP,
            pid=None if action is NodeRuntimeAction.STOP else 1234,
            process_start_ticks=None if action is NodeRuntimeAction.STOP else 5678,
            boot_id=None
            if action is NodeRuntimeAction.STOP
            else UUID("10000000-0000-0000-0000-000000000001"),
            executable_sha256=None
            if action is NodeRuntimeAction.STOP
            else "a" * 64,
        )


class FailingSmokeProbe:
    def check(self, spec: NodeRuntimeSpec) -> None:
        raise NodeSupervisorError("node_api_smoke_failed")


class EventuallyHealthySmokeProbe:
    def __init__(self) -> None:
        self.calls = 0

    def check(self, spec: NodeRuntimeSpec) -> None:
        self.calls += 1
        if self.calls == 1:
            raise NodeSupervisorError("node_api_smoke_failed")


def test_supervisor_provisions_smokes_and_binds_the_applied_identity(tmp_path: Path) -> None:
    root = tmp_path / "nodes"
    root.mkdir(mode=0o750)
    process = RecordingProcessController()
    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root, group_id=None),
        process=process,
        smoke=HealthySmokeProbe(),
        port_is_bindable=lambda port: False,
    )
    command = NodeRuntimeCommand.for_node(
        NodeRuntimeAction.PROVISION_START,
        runtime_spec(),
    )

    observation = supervisor.execute(command)

    assert process.commands == [(NodeRuntimeAction.PROVISION_START, runtime_spec().node_id)]
    assert observation.state is NodeState.RUNNING
    assert observation.health is NodeHealth.HEALTHY
    assert observation.management_fresh is True
    assert observation.config_compatible is True
    assert observation.applied_revision == 3
    assert observation.process_id == 1234
    assert observation.process_start_ticks == 5678
    assert observation.process_boot_id == UUID("10000000-0000-0000-0000-000000000001")
    assert observation.config_sha256 == command.config.sha256  # type: ignore[union-attr]
    assert observation.release_id == "release-2026.08.12"


def test_supervisor_stop_requires_process_and_all_three_listeners_to_be_gone(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes"
    root.mkdir(mode=0o750)
    process = RecordingProcessController()
    observed_ports: list[int] = []

    def port_is_bindable(port: int) -> bool:
        observed_ports.append(port)
        return True

    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root, group_id=None),
        process=process,
        smoke=HealthySmokeProbe(),
        port_is_bindable=port_is_bindable,
    )

    observation = supervisor.execute(
        NodeRuntimeCommand.for_node(NodeRuntimeAction.STOP, runtime_spec())
    )

    assert observation.state is NodeState.STOPPED
    assert observation.health is NodeHealth.UNKNOWN
    assert observed_ports == [12001, 13001, 14001]


def test_failed_start_smoke_stops_only_that_exact_process(tmp_path: Path) -> None:
    root = tmp_path / "nodes"
    root.mkdir(mode=0o750)
    process = RecordingProcessController()
    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root, group_id=None),
        process=process,
        smoke=FailingSmokeProbe(),
        port_is_bindable=lambda port: True,
        smoke_attempts=2,
        sleep=lambda seconds: None,
    )

    with pytest.raises(NodeSupervisorError, match="node_api_smoke_failed"):
        supervisor.execute(
            NodeRuntimeCommand.for_node(
                NodeRuntimeAction.PROVISION_START,
                runtime_spec(),
            )
        )

    assert process.commands == [
        (NodeRuntimeAction.PROVISION_START, runtime_spec().node_id),
        (NodeRuntimeAction.STOP, runtime_spec().node_id),
    ]


def test_supervisor_retries_transient_smoke_without_restarting(tmp_path: Path) -> None:
    root = tmp_path / "nodes-retry"
    root.mkdir(mode=0o750)
    process = RecordingProcessController()
    smoke = EventuallyHealthySmokeProbe()
    delays: list[float] = []
    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root, group_id=None),
        process=process,
        smoke=smoke,
        port_is_bindable=lambda port: False,
        smoke_attempts=2,
        retry_delay_seconds=0.1,
        sleep=delays.append,
    )

    observation = supervisor.execute(
        NodeRuntimeCommand.for_node(NodeRuntimeAction.PROVISION_START, runtime_spec())
    )

    assert observation.health is NodeHealth.HEALTHY
    assert smoke.calls == 2
    assert delays == [0.1]
    assert process.commands == [
        (NodeRuntimeAction.PROVISION_START, runtime_spec().node_id)
    ]


def test_supervisor_refuses_missing_or_tampered_config_before_process_mutation(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes-config"
    root.mkdir(mode=0o750)
    process = RecordingProcessController()
    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root, group_id=None),
        process=process,
        smoke=HealthySmokeProbe(),
        port_is_bindable=lambda port: False,
    )

    with pytest.raises(NodeSupervisorError, match="node_config_not_applied"):
        supervisor.execute(
            NodeRuntimeCommand.for_node(NodeRuntimeAction.START, runtime_spec())
        )
    tampered = RenderedNodeConfig.from_content("paths: {}\n")
    with pytest.raises(NodeSupervisorError, match="node_rendered_config_mismatch"):
        supervisor.execute(
            NodeRuntimeCommand(
                action=NodeRuntimeAction.PROVISION_START,
                spec=runtime_spec(),
                config=tampered,
            )
        )
    assert process.commands == []


class WrongReleaseProcessController(RecordingProcessController):
    def execute(
        self,
        action: NodeRuntimeAction,
        spec: NodeRuntimeSpec,
    ) -> NodeProcessSnapshot:
        snapshot = super().execute(action, spec)
        if not snapshot.active:
            return snapshot
        return NodeProcessSnapshot(
            active=True,
            pid=snapshot.pid,
            process_start_ticks=snapshot.process_start_ticks,
            boot_id=snapshot.boot_id,
            executable_sha256="d" * 64,
        )


def test_supervisor_stops_a_process_with_the_wrong_release_identity(tmp_path: Path) -> None:
    root = tmp_path / "nodes-release"
    root.mkdir(mode=0o750)
    process = WrongReleaseProcessController()
    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root, group_id=None),
        process=process,
        smoke=HealthySmokeProbe(),
        port_is_bindable=lambda port: True,
    )

    with pytest.raises(NodeSupervisorError, match="node_process_release_mismatch"):
        supervisor.execute(
            NodeRuntimeCommand.for_node(
                NodeRuntimeAction.PROVISION_START,
                runtime_spec(),
            )
        )

    assert process.commands[-1] == (NodeRuntimeAction.STOP, runtime_spec().node_id)


def test_supervisor_stop_rejects_a_listener_that_survived_the_process(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes-listener"
    root.mkdir(mode=0o750)
    process = RecordingProcessController()
    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(root=root, group_id=None),
        process=process,
        smoke=HealthySmokeProbe(),
        port_is_bindable=lambda port: False,
    )

    with pytest.raises(NodeSupervisorError, match="node_listener_still_active"):
        supervisor.execute(
            NodeRuntimeCommand.for_node(NodeRuntimeAction.STOP, runtime_spec())
        )


def test_systemd_adapter_can_only_address_the_exact_uuid_instance(tmp_path: Path) -> None:
    calls: list[tuple[str, ...]] = []
    proc_root = tmp_path / "proc"
    proc_root.mkdir()

    def run(arguments: tuple[str, ...]) -> CompletedProcess[str]:
        calls.append(arguments)
        if "show" in arguments:
            return CompletedProcess(
                arguments,
                0,
                "ActiveState=inactive\nMainPID=0\n",
                "",
            )
        return CompletedProcess(arguments, 0, "", "")

    controller = SystemdNodeProcessController(
        systemctl=Path("/usr/bin/systemctl"),
        run=run,
        proc_root=proc_root,
    )

    snapshot = controller.execute(NodeRuntimeAction.STOP, runtime_spec())

    unit = "rtsp-proxy-media@00000000-0000-0000-0000-000000000001.service"
    assert calls == [
        ("/usr/bin/systemctl", "--no-ask-password", "stop", unit),
        (
            "/usr/bin/systemctl",
            "--no-pager",
            "show",
            unit,
            "--property=ActiveState",
            "--property=MainPID",
        ),
    ]
    assert snapshot.active is False


def test_systemd_adapter_binds_active_pid_start_boot_and_binary_identity(
    tmp_path: Path,
) -> None:
    binary = tmp_path / "mediamtx"
    binary.write_bytes(b"verified-binary")
    proc_root = tmp_path / "proc"
    process_root = proc_root / "1234"
    process_root.mkdir(parents=True)
    (proc_root / "sys/kernel/random").mkdir(parents=True)
    (proc_root / "sys/kernel/random/boot_id").write_text(
        "10000000-0000-0000-0000-000000000001\n",
        encoding="ascii",
    )
    stat_fields = ["S", *("0" for _ in range(18)), "5678"]
    (process_root / "stat").write_text(
        f"1234 (mediamtx worker) {' '.join(stat_fields)}\n",
        encoding="ascii",
    )
    (process_root / "exe").symlink_to(binary)

    def run(arguments: tuple[str, ...]) -> CompletedProcess[str]:
        return CompletedProcess(
            arguments,
            0,
            "ActiveState=active\nMainPID=1234\n",
            "",
        )

    snapshot = SystemdNodeProcessController(
        systemctl=Path("/usr/bin/systemctl"),
        run=run,
        proc_root=proc_root,
    ).execute(NodeRuntimeAction.OBSERVE, runtime_spec())

    assert snapshot == NodeProcessSnapshot(
        active=True,
        pid=1234,
        process_start_ticks=5678,
        boot_id=UUID("10000000-0000-0000-0000-000000000001"),
        executable_sha256=hashlib.sha256(b"verified-binary").hexdigest(),
    )


def test_systemd_adapter_rejects_unsafe_path_command_failure_and_bad_status(
    tmp_path: Path,
) -> None:
    with pytest.raises(ValueError, match="systemctl_path_must_be_absolute"):
        SystemdNodeProcessController(systemctl=Path("systemctl"))

    def failed(arguments: tuple[str, ...]) -> CompletedProcess[str]:
        return CompletedProcess(arguments, 1, "", "secret diagnostic")

    with pytest.raises(NodeSupervisorError, match="systemd_node_command_failed"):
        SystemdNodeProcessController(
            systemctl=Path("/usr/bin/systemctl"),
            run=failed,
            proc_root=tmp_path,
        ).execute(NodeRuntimeAction.START, runtime_spec())

    for output, error in (
        ("ActiveState=inactive\nActiveState=inactive\nMainPID=0\n", "status_invalid"),
        ("ActiveState=inactive\nMainPID=12\n", "inactive_node_has_pid"),
        ("ActiveState=active\nMainPID=0\n", "active_node_missing_pid"),
    ):
        with pytest.raises(NodeSupervisorError, match=error):
            def show(
                arguments: tuple[str, ...],
                output: str = output,
            ) -> CompletedProcess[str]:
                return CompletedProcess(arguments, 0, output, "")

            SystemdNodeProcessController(
                systemctl=Path("/usr/bin/systemctl"),
                run=show,
                proc_root=tmp_path,
            ).execute(NodeRuntimeAction.OBSERVE, runtime_spec())


def test_direct_contract_adapter_starts_restarts_and_stops_only_one_node(
    tmp_path: Path,
) -> None:
    binary = tmp_path / "mediamtx-test"
    binary.write_text("#!/bin/sh\nexec /bin/sleep 30\n", encoding="utf-8")
    binary.chmod(0o755)
    config_root = tmp_path / "nodes"
    config_root.mkdir(mode=0o750)
    spec = runtime_spec()
    SecureNodeConfigStore(root=config_root, group_id=None).install(
        spec,
        MediaNodeConfigRenderer().render(spec),
    )
    observed_pids: list[int] = []

    def identity(proc_root: Path, pid: int) -> NodeProcessSnapshot:
        observed_pids.append(pid)
        return NodeProcessSnapshot(
            active=True,
            pid=pid,
            process_start_ticks=pid + 100,
            boot_id=UUID("10000000-0000-0000-0000-000000000001"),
            executable_sha256="a" * 64,
        )

    controller = DirectNodeProcessController(
        mediamtx_binary=binary,
        config_root=config_root,
        process_identity=identity,
    )
    try:
        started = controller.execute(NodeRuntimeAction.START, spec)
        restarted = controller.execute(NodeRuntimeAction.RESTART, spec)
        stopped = controller.execute(NodeRuntimeAction.STOP, spec)
    finally:
        controller.close()

    assert started.active is True
    assert restarted.active is True
    assert started.pid != restarted.pid
    assert observed_pids == [started.pid, restarted.pid]
    assert stopped.active is False


class SmokeHttpHandler(http.server.BaseHTTPRequestHandler):
    global_config: ClassVar[dict[str, object]] = {}

    def do_GET(self) -> None:
        if self.path == "/v3/config/global/get":
            payload = json.dumps(self.global_config).encode()
        elif self.path == "/metrics":
            payload = b"metrics"
        else:
            self.send_error(404)
            return
        self.send_response(200)
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def log_message(self, format: str, *args: object) -> None:
        pass


def test_smoke_probe_checks_api_metrics_and_plain_rtsp_tcp() -> None:
    api = http.server.ThreadingHTTPServer(("127.0.0.1", 0), SmokeHttpHandler)
    metrics = http.server.ThreadingHTTPServer(("127.0.0.1", 0), SmokeHttpHandler)
    rtsp = socket.socket()
    rtsp.bind(("127.0.0.1", 0))
    rtsp.listen(1)
    api_port = int(api.server_address[1])
    metrics_port = int(metrics.server_address[1])
    rtsp_port = int(rtsp.getsockname()[1])
    spec = NodeRuntimeSpec(
        node_id=runtime_spec().node_id,
        external_port=rtsp_port,
        api_port=api_port,
        metrics_port=metrics_port,
        desired_revision=1,
        release_id="release-2026.08.12",
        mediamtx_binary_sha256="a" * 64,
    )
    SmokeHttpHandler.global_config = {
        "api": True,
        "apiAddress": f"127.0.0.1:{api_port}",
        "metrics": True,
        "metricsAddress": f"127.0.0.1:{metrics_port}",
        "rtsp": True,
        "rtspAddress": f":{rtsp_port}",
        "rtspTransports": ["tcp"],
        "rtspEncryption": "no",
        "rtmp": False,
        "hls": False,
        "webrtc": False,
        "srt": False,
    }

    def answer_rtsp() -> None:
        connection, _ = rtsp.accept()
        with connection:
            request = connection.recv(8192)
            assert request.startswith(b"OPTIONS rtsp://")
            assert b"RTSP/1.0" in request
            connection.sendall(b"RTSP/1.0 200 OK\r\nCSeq: 1\r\n\r\n")

    threads = (
        Thread(target=api.serve_forever),
        Thread(target=metrics.serve_forever),
        Thread(target=answer_rtsp),
    )
    for thread in threads:
        thread.start()
    try:
        MediaNodeSmokeProbe(timeout_seconds=1).check(spec)
    finally:
        api.shutdown()
        metrics.shutdown()
        api.server_close()
        metrics.server_close()
        rtsp.close()
        for thread in threads:
            thread.join(timeout=1)


def test_control_plane_uses_one_bounded_unix_request_for_an_exact_node(
) -> None:
    temporary = tempfile.TemporaryDirectory(prefix="rtsp-node-", dir="/tmp")
    socket_path = Path(temporary.name) / "runtime.sock"
    listener = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    listener.bind(str(socket_path))
    listener.listen(1)
    captured: dict[str, object] = {}

    def answer() -> None:
        connection, _ = listener.accept()
        with connection:
            request = connection.makefile("rb").readline(65537)
            captured.update(json.loads(request))
            connection.sendall(
                (
                    json.dumps(
                        {
                            "schema_version": 1,
                            "ok": True,
                            "observation": {
                                "state": "running",
                                "health": "healthy",
                                "management_fresh": True,
                                "config_compatible": True,
                                "applied_revision": 3,
                                "process_id": 1234,
                                "process_start_ticks": 5678,
                                "process_boot_id": "10000000-0000-0000-0000-000000000001",
                                "config_sha256": "b" * 64,
                                "release_id": "release-2026.08.12",
                            },
                            "error": None,
                        },
                        separators=(",", ":"),
                    )
                    + "\n"
                ).encode()
            )

    server = Thread(target=answer)
    server.start()
    node = MediaNode(
        id=runtime_spec().node_id,
        name="media-a",
        external_port=runtime_spec().external_port,
        api_port=runtime_spec().api_port,
        metrics_port=runtime_spec().metrics_port,
        release_id=runtime_spec().release_id,
        mediamtx_binary_sha256=runtime_spec().mediamtx_binary_sha256,
        desired_revision=3,
    )

    observation = UnixNodeRuntimeClient(
        socket_path=socket_path,
        timeout_seconds=1,
    ).execute(NodeRuntimeAction.PROVISION_START, node)

    server.join(timeout=1)
    listener.close()
    temporary.cleanup()
    assert captured["schema_version"] == 1
    assert captured["action"] == "provision_start"
    assert captured["spec"] == {
        "node_id": str(node.id),
        "external_port": 12001,
        "api_port": 13001,
        "metrics_port": 14001,
        "desired_revision": 3,
        "release_id": "release-2026.08.12",
        "mediamtx_binary_sha256": "a" * 64,
    }
    assert isinstance(captured["config"], dict)
    assert observation.state is NodeState.RUNNING
    assert observation.process_id == 1234


def test_runtime_client_rejects_oversized_or_malformed_helper_responses(
) -> None:
    temporary = tempfile.TemporaryDirectory(prefix="rtsp-node-", dir="/tmp")
    socket_path = Path(temporary.name) / "runtime.sock"
    listener = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    listener.bind(str(socket_path))
    listener.listen(1)

    def answer() -> None:
        connection, _ = listener.accept()
        with connection:
            connection.makefile("rb").readline(65537)
            connection.sendall(b'{"ok":true,"unexpected":"field"}\n')

    server = Thread(target=answer)
    server.start()
    node = MediaNode(
        id=runtime_spec().node_id,
        name="media-a",
        external_port=runtime_spec().external_port,
        api_port=runtime_spec().api_port,
        metrics_port=runtime_spec().metrics_port,
        release_id=runtime_spec().release_id,
        mediamtx_binary_sha256=runtime_spec().mediamtx_binary_sha256,
        desired_revision=3,
    )

    with pytest.raises(RuntimeError, match="node_runtime_response_invalid"):
        UnixNodeRuntimeClient(socket_path=socket_path, timeout_seconds=1).execute(
            NodeRuntimeAction.OBSERVE,
            node,
        )

    server.join(timeout=1)
    listener.close()
    temporary.cleanup()


def test_runtime_client_reports_missing_socket_without_exposing_os_error(
    tmp_path: Path,
) -> None:
    node = MediaNode(
        id=runtime_spec().node_id,
        name="media-a",
        external_port=runtime_spec().external_port,
        api_port=runtime_spec().api_port,
        metrics_port=runtime_spec().metrics_port,
        release_id=runtime_spec().release_id,
        mediamtx_binary_sha256=runtime_spec().mediamtx_binary_sha256,
        desired_revision=3,
    )

    with pytest.raises(NodeSupervisorError, match="node_runtime_unavailable"):
        UnixNodeRuntimeClient(
            socket_path=tmp_path / "missing.sock",
            timeout_seconds=0.1,
        ).execute(NodeRuntimeAction.OBSERVE, node)


def test_root_helper_rejects_a_port_outside_its_allowlist_before_process_mutation(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes"
    root.mkdir(mode=0o750)
    process = RecordingProcessController()
    server = UnixNodeSupervisorServer(
        supervisor=LinuxNodeSupervisor(
            config_store=SecureNodeConfigStore(root=root, group_id=None),
            process=process,
            smoke=HealthySmokeProbe(),
            port_is_bindable=lambda port: False,
        ),
        policy=NodeRuntimePolicy(
            external_port_start=12500,
            external_port_end=12599,
            api_port_start=13000,
            api_port_end=13099,
            metrics_port_start=14000,
            metrics_port_end=14099,
            release_id="release-2026.08.12",
            mediamtx_binary_sha256="a" * 64,
        ),
    )
    client_socket, server_socket = socket.socketpair()
    request = {
        "schema_version": 1,
        "action": "provision_start",
        "spec": {
            "node_id": str(runtime_spec().node_id),
            "external_port": runtime_spec().external_port,
            "api_port": runtime_spec().api_port,
            "metrics_port": runtime_spec().metrics_port,
            "desired_revision": 3,
            "release_id": runtime_spec().release_id,
            "mediamtx_binary_sha256": "a" * 64,
        },
        "config": {
            "content": MediaNodeConfigRenderer().render(runtime_spec()).content,
            "sha256": MediaNodeConfigRenderer().render(runtime_spec()).sha256,
        },
    }
    client_socket.sendall((json.dumps(request) + "\n").encode())

    server.serve_connection(server_socket)

    response = json.loads(client_socket.makefile("rb").readline())
    client_socket.close()
    server_socket.close()
    assert response == {
        "schema_version": 1,
        "ok": False,
        "observation": None,
        "error": "node_external_port_not_allowed",
    }
    assert process.commands == []


def test_root_helper_executes_a_valid_request_and_returns_bound_observation(
    tmp_path: Path,
) -> None:
    root = tmp_path / "nodes-valid"
    root.mkdir(mode=0o750)
    process = RecordingProcessController()
    server = UnixNodeSupervisorServer(
        supervisor=LinuxNodeSupervisor(
            config_store=SecureNodeConfigStore(root=root, group_id=None),
            process=process,
            smoke=HealthySmokeProbe(),
            port_is_bindable=lambda port: False,
        ),
        policy=NodeRuntimePolicy(
            external_port_start=12000,
            external_port_end=12099,
            api_port_start=13000,
            api_port_end=13099,
            metrics_port_start=14000,
            metrics_port_end=14099,
            release_id="release-2026.08.12",
            mediamtx_binary_sha256="a" * 64,
        ),
    )
    client_socket, server_socket = socket.socketpair()
    config = MediaNodeConfigRenderer().render(runtime_spec())
    request = {
        "schema_version": 1,
        "action": "provision_start",
        "spec": {
            "node_id": str(runtime_spec().node_id),
            "external_port": runtime_spec().external_port,
            "api_port": runtime_spec().api_port,
            "metrics_port": runtime_spec().metrics_port,
            "desired_revision": runtime_spec().desired_revision,
            "release_id": runtime_spec().release_id,
            "mediamtx_binary_sha256": runtime_spec().mediamtx_binary_sha256,
        },
        "config": {"content": config.content, "sha256": config.sha256},
    }
    client_socket.sendall((json.dumps(request) + "\n").encode())

    server.serve_connection(server_socket)

    response = json.loads(client_socket.makefile("rb").readline())
    client_socket.close()
    server_socket.close()
    assert response["ok"] is True
    assert response["error"] is None
    assert response["observation"]["state"] == "running"
    assert response["observation"]["process_id"] == 1234


@pytest.mark.parametrize(
    ("changes", "error"),
    (
        ({"external_port": 11999}, "node_external_port_not_allowed"),
        ({"api_port": 12999}, "node_api_port_not_allowed"),
        ({"metrics_port": 13999}, "node_metrics_port_not_allowed"),
        ({"release_id": "wrong"}, "node_release_not_allowed"),
    ),
)
def test_root_helper_policy_rejects_every_out_of_contract_dimension(
    changes: dict[str, object],
    error: str,
) -> None:
    policy = NodeRuntimePolicy(
        external_port_start=12000,
        external_port_end=12099,
        api_port_start=13000,
        api_port_end=13099,
        metrics_port_start=14000,
        metrics_port_end=14099,
        release_id="release-2026.08.12",
        mediamtx_binary_sha256="a" * 64,
    )
    values: dict[str, object] = {
        "node_id": runtime_spec().node_id,
        "external_port": 12001,
        "api_port": 13001,
        "metrics_port": 14001,
        "desired_revision": 3,
        "release_id": "release-2026.08.12",
        "mediamtx_binary_sha256": "a" * 64,
    }
    values.update(changes)

    with pytest.raises(NodeSupervisorError, match=error):
        policy.validate(NodeRuntimeSpec(**values))  # type: ignore[arg-type]


def test_helper_settings_reject_overlap_and_non_absolute_privileged_paths() -> None:
    with pytest.raises(ValueError, match="node_helper_port_ranges_overlap"):
        helper_settings(api_port_start=12099)
    with pytest.raises(ValueError, match="node_helper_path_invalid"):
        helper_settings(config_root=Path("relative"))

    settings = helper_settings()
    assert settings.policy().release_id == "release-2026.08.12"


def helper_settings(
    *,
    api_port_start: int = 13000,
    config_root: Path = Path("/etc/rtsp-proxy/nodes"),
) -> NodeHelperSettings:
    return NodeHelperSettings(
        config_root=config_root,
        external_port_start=12000,
        external_port_end=12099,
        api_port_start=api_port_start,
        api_port_end=13099,
        metrics_port_start=14000,
        metrics_port_end=14099,
        release_id="release-2026.08.12",
        mediamtx_binary_sha256="a" * 64,
    )
