from __future__ import annotations

import base64
import errno
import hashlib
import json
import os
import secrets
import socket
import stat
import subprocess
import time
import urllib.error
import urllib.request
from collections.abc import Callable, Mapping
from concurrent.futures import ThreadPoolExecutor
from contextlib import suppress
from dataclasses import dataclass
from pathlib import Path
from subprocess import CompletedProcess
from threading import BoundedSemaphore, Lock
from typing import Protocol
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, ValidationError, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

from rtsp_proxy.nodes import (
    MediaNode,
    NodeHealth,
    NodeRuntimeAction,
    NodeRuntimeObservation,
    NodeState,
)


@dataclass(frozen=True, slots=True)
class NodeRuntimeSpec:
    node_id: UUID
    external_port: int
    api_port: int
    metrics_port: int
    desired_revision: int
    release_id: str
    mediamtx_binary_sha256: str

    def __post_init__(self) -> None:
        ports = (self.external_port, self.api_port, self.metrics_port)
        if any(port < 1 or port > 65535 for port in ports):
            raise ValueError("node_port_invalid")
        if len(set(ports)) != len(ports):
            raise ValueError("node_ports_not_unique")
        if self.desired_revision < 1:
            raise ValueError("node_desired_revision_invalid")
        if not self.release_id or len(self.release_id) > 128:
            raise ValueError("node_release_id_invalid")
        if len(self.mediamtx_binary_sha256) != 64 or any(
            character not in "0123456789abcdef" for character in self.mediamtx_binary_sha256
        ):
            raise ValueError("node_binary_sha256_invalid")


@dataclass(frozen=True, slots=True)
class RenderedNodeConfig:
    content: str
    sha256: str

    @classmethod
    def from_content(cls, content: str) -> RenderedNodeConfig:
        if not content.endswith("\n"):
            raise ValueError("node_config_final_newline_required")
        return cls(
            content=content,
            sha256=hashlib.sha256(content.encode("utf-8")).hexdigest(),
        )


@dataclass(frozen=True, slots=True)
class NodeManagementCredentials:
    username: str
    password: str

    def __post_init__(self) -> None:
        if (
            not self.username.startswith("node-")
            or len(self.username) > 64
            or len(self.password) < 32
            or len(self.password) > 128
            or any(character.isspace() for character in self.password)
        ):
            raise ValueError("node_management_credentials_invalid")


@dataclass(frozen=True, slots=True)
class NodeReaderCredentials:
    username: str
    password: str

    def __post_init__(self) -> None:
        if (
            not self.username.startswith("reader-")
            or len(self.username) > 64
            or len(self.password) < 32
            or len(self.password) > 128
            or any(character.isspace() for character in self.password)
        ):
            raise ValueError("node_reader_credentials_invalid")


@dataclass(frozen=True, slots=True)
class NodeOperationDeadline:
    """One monotonic end-to-end budget shared by every lifecycle adapter."""

    expires_monotonic: float
    monotonic: Callable[[], float] = time.monotonic

    def remaining_seconds(self, *, maximum: float | None = None) -> float:
        remaining = self.expires_monotonic - self.monotonic()
        if remaining <= 0:
            raise NodeSupervisorError("node_runtime_operation_timeout")
        return remaining if maximum is None else min(remaining, maximum)

    def before(self, seconds: float) -> NodeOperationDeadline:
        if seconds <= 0:
            raise ValueError("node_runtime_deadline_reserve_invalid")
        deadline = NodeOperationDeadline(
            expires_monotonic=self.expires_monotonic - seconds,
            monotonic=self.monotonic,
        )
        deadline.remaining_seconds()
        return deadline


class MediaNodeConfigRenderer:
    """Render the entire pinned MediaMTX global config from one typed spec."""

    def render(
        self,
        spec: NodeRuntimeSpec,
        credentials: NodeManagementCredentials,
        reader_credentials: NodeReaderCredentials | None = None,
    ) -> RenderedNodeConfig:
        reader = ""
        if reader_credentials is not None:
            reader = f"""  - user: {reader_credentials.username}
    pass: {reader_credentials.password}
    ips: [\"127.0.0.1\", \"::1\"]
    permissions:
      - action: read
        path: __rtsp_proxy_runtime_probe
"""
        content = f"""# Generated by rtsp-proxy. Do not edit.
logLevel: info
logDestinations: [stdout]
logStructured: true
authMethod: internal
authInternalUsers:
  - user: {credentials.username}
    pass: {credentials.password}
    ips: [\"127.0.0.1\", \"::1\"]
    permissions:
      - action: api
      - action: metrics
{reader}api: true
apiAddress: 127.0.0.1:{spec.api_port}
apiEncryption: false
apiAllowOrigins: []
apiTrustedProxies: []
metrics: true
metricsAddress: 127.0.0.1:{spec.metrics_port}
metricsEncryption: false
metricsAllowOrigins: []
metricsTrustedProxies: []
pprof: false
playback: false
rtsp: true
rtspTransports: [tcp]
rtspEncryption: \"no\"
rtspAddress: :{spec.external_port}
rtspAuthMethods: [basic]
rtspTrustedProxies: []
rtmp: false
hls: false
webrtc: false
srt: false
moq: false
paths: {{}}
"""
        return RenderedNodeConfig.from_content(content)


@dataclass(frozen=True, slots=True)
class NodeRuntimeCommand:
    action: NodeRuntimeAction
    spec: NodeRuntimeSpec
    config: RenderedNodeConfig | None = None

    def __post_init__(self) -> None:
        if self.config is not None:
            raise ValueError("runtime_config_not_allowed")

    @classmethod
    def for_node(
        cls,
        action: NodeRuntimeAction,
        spec: NodeRuntimeSpec,
    ) -> NodeRuntimeCommand:
        return cls(action=action, spec=spec)


class SecureNodeConfigStore:
    """Install one generated config without following node-controlled paths."""

    def __init__(
        self,
        *,
        root: Path,
        owner_uid: int | None = None,
        binary_path: Path | None = None,
        binary_catalog: Mapping[tuple[str, str], Path] | None = None,
    ) -> None:
        if not root.is_absolute():
            raise ValueError("node_config_root_must_be_absolute")
        self._root = root
        self._owner_uid = os.geteuid() if owner_uid is None else owner_uid
        self._binary_path = binary_path
        self._binary_catalog = dict(binary_catalog or {})
        if binary_path is not None and self._binary_catalog:
            raise ValueError("node_binary_catalog_ambiguous")

    def provision(
        self, spec: NodeRuntimeSpec
    ) -> tuple[RenderedNodeConfig, NodeManagementCredentials]:
        credentials = self._new_credentials(spec)
        reader_credentials = self._new_reader_credentials(spec)
        rendered = MediaNodeConfigRenderer().render(spec, credentials, reader_credentials)
        self.install(
            spec,
            rendered,
            credentials=credentials,
            reader_credentials=reader_credentials,
        )
        return rendered, credentials

    def expected(
        self,
        spec: NodeRuntimeSpec,
    ) -> tuple[RenderedNodeConfig, NodeManagementCredentials] | None:
        credentials = self.credentials(spec)
        reader_credentials = self.reader_credentials(spec)
        if credentials is None:
            return None
        return (
            MediaNodeConfigRenderer().render(spec, credentials, reader_credentials),
            credentials,
        )

    def rebind_release(self, spec: NodeRuntimeSpec) -> None:
        if self._binary_path is None and not self._binary_catalog:
            return
        root_fd = self._open_root()
        try:
            node_fd = self._open_node(root_fd, str(spec.node_id))
            try:
                self._install_runtime_environment(node_fd, spec)
            finally:
                os.close(node_fd)
        finally:
            os.close(root_fd)

    def install(
        self,
        spec: NodeRuntimeSpec,
        rendered: RenderedNodeConfig,
        *,
        credentials: NodeManagementCredentials,
        reader_credentials: NodeReaderCredentials | None = None,
    ) -> Path:
        if hashlib.sha256(rendered.content.encode("utf-8")).hexdigest() != rendered.sha256:
            raise ValueError("node_config_digest_mismatch")
        root_fd = self._open_root()
        try:
            node_name = str(spec.node_id)
            with suppress(FileExistsError):
                os.mkdir(node_name, mode=0o700, dir_fd=root_fd)
                os.fsync(root_fd)
            node_fd = self._open_node(root_fd, node_name)
            try:
                self._install_at(node_fd, rendered)
                self._install_credentials(node_fd, credentials)
                if reader_credentials is not None:
                    self._install_reader_credentials(node_fd, reader_credentials)
                self._install_runtime_environment(node_fd, spec)
            finally:
                os.close(node_fd)
        finally:
            os.close(root_fd)
        return self._root / str(spec.node_id) / "mediamtx.yml"

    def digest(self, spec: NodeRuntimeSpec) -> str | None:
        root_fd = self._open_root()
        try:
            try:
                node_fd = self._open_node(root_fd, str(spec.node_id))
            except ValueError:
                return None
            try:
                flags = os.O_RDONLY
                if hasattr(os, "O_CLOEXEC"):
                    flags |= os.O_CLOEXEC
                if hasattr(os, "O_NOFOLLOW"):
                    flags |= os.O_NOFOLLOW
                try:
                    descriptor = os.open("mediamtx.yml", flags, dir_fd=node_fd)
                except FileNotFoundError:
                    return None
                try:
                    file_stat = os.fstat(descriptor)
                    mode = stat.S_IMODE(file_stat.st_mode)
                    if (
                        mode != 0o600
                        or not stat.S_ISREG(file_stat.st_mode)
                        or file_stat.st_uid != self._owner_uid
                    ):
                        raise ValueError("node_config_file_unsafe")
                    digest = hashlib.sha256()
                    while chunk := os.read(descriptor, 1024 * 1024):
                        digest.update(chunk)
                    return digest.hexdigest()
                finally:
                    os.close(descriptor)
            finally:
                os.close(node_fd)
        finally:
            os.close(root_fd)

    def credentials(self, spec: NodeRuntimeSpec) -> NodeManagementCredentials | None:
        root_fd = self._open_root()
        try:
            try:
                node_fd = self._open_node(root_fd, str(spec.node_id))
            except ValueError:
                return None
            try:
                try:
                    payload = self._read_private_file(node_fd, "management.json")
                except FileNotFoundError:
                    return None
                try:
                    raw = json.loads(payload)
                    if not isinstance(raw, dict) or set(raw) != {"username", "password"}:
                        raise ValueError
                    return NodeManagementCredentials(
                        username=str(raw["username"]),
                        password=str(raw["password"]),
                    )
                except (TypeError, ValueError, json.JSONDecodeError) as error:
                    raise ValueError("node_management_credentials_unsafe") from error
            finally:
                os.close(node_fd)
        finally:
            os.close(root_fd)

    def reader_credentials(self, spec: NodeRuntimeSpec) -> NodeReaderCredentials | None:
        root_fd = self._open_root()
        try:
            try:
                node_fd = self._open_node(root_fd, str(spec.node_id))
            except ValueError:
                return None
            try:
                try:
                    payload = self._read_private_file(node_fd, "reader.json")
                except FileNotFoundError:
                    return None
                try:
                    raw = json.loads(payload)
                    if not isinstance(raw, dict) or set(raw) != {"username", "password"}:
                        raise ValueError
                    return NodeReaderCredentials(
                        username=str(raw["username"]),
                        password=str(raw["password"]),
                    )
                except (TypeError, ValueError, json.JSONDecodeError) as error:
                    raise ValueError("node_reader_credentials_unsafe") from error
            finally:
                os.close(node_fd)
        finally:
            os.close(root_fd)

    def _open_root(self) -> int:
        flags = os.O_RDONLY | os.O_DIRECTORY
        if hasattr(os, "O_CLOEXEC"):
            flags |= os.O_CLOEXEC
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        try:
            descriptor = os.open(self._root, flags)
        except OSError as error:
            raise ValueError("node_config_root_unsafe") from error
        root_stat = os.fstat(descriptor)
        mode = stat.S_IMODE(root_stat.st_mode)
        if (
            mode & 0o077
            or not stat.S_ISDIR(root_stat.st_mode)
            or root_stat.st_uid != self._owner_uid
        ):
            os.close(descriptor)
            raise ValueError("node_config_root_unsafe")
        return descriptor

    def _open_node(self, root_fd: int, node_name: str) -> int:
        flags = os.O_RDONLY | os.O_DIRECTORY
        if hasattr(os, "O_CLOEXEC"):
            flags |= os.O_CLOEXEC
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        try:
            descriptor = os.open(node_name, flags, dir_fd=root_fd)
        except OSError as error:
            raise ValueError("node_config_directory_unsafe") from error
        node_stat = os.fstat(descriptor)
        mode = stat.S_IMODE(node_stat.st_mode)
        if (
            mode != 0o700
            or not stat.S_ISDIR(node_stat.st_mode)
            or node_stat.st_uid != self._owner_uid
        ):
            os.close(descriptor)
            raise ValueError("node_config_directory_unsafe")
        return descriptor

    def _install_at(self, node_fd: int, rendered: RenderedNodeConfig) -> None:
        temporary_name = f".mediamtx.{secrets.token_hex(12)}.tmp"
        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
        if hasattr(os, "O_CLOEXEC"):
            flags |= os.O_CLOEXEC
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        descriptor: int | None = None
        try:
            descriptor = os.open(temporary_name, flags, 0o600, dir_fd=node_fd)
            content = rendered.content.encode("utf-8")
            written = 0
            while written < len(content):
                count = os.write(descriptor, content[written:])
                if count <= 0:
                    raise OSError("short node config write")
                written += count
            os.fchmod(descriptor, 0o600)
            os.fsync(descriptor)
            os.close(descriptor)
            descriptor = None
            os.rename(
                temporary_name,
                "mediamtx.yml",
                src_dir_fd=node_fd,
                dst_dir_fd=node_fd,
            )
            os.fsync(node_fd)
        except Exception:
            if descriptor is not None:
                os.close(descriptor)
            with suppress(FileNotFoundError):
                os.unlink(temporary_name, dir_fd=node_fd)
            raise

    def _install_credentials(
        self,
        node_fd: int,
        credentials: NodeManagementCredentials,
    ) -> None:
        payload = (
            json.dumps(
                {"username": credentials.username, "password": credentials.password},
                separators=(",", ":"),
                sort_keys=True,
            )
            + "\n"
        )
        self._replace_private_file(node_fd, "management.json", payload.encode("utf-8"))

    def _install_reader_credentials(
        self,
        node_fd: int,
        credentials: NodeReaderCredentials,
    ) -> None:
        payload = (
            json.dumps(
                {"username": credentials.username, "password": credentials.password},
                separators=(",", ":"),
                sort_keys=True,
            )
            + "\n"
        )
        self._replace_private_file(node_fd, "reader.json", payload.encode("utf-8"))

    def _install_runtime_environment(self, node_fd: int, spec: NodeRuntimeSpec) -> None:
        binary_path = self._binary_path
        if self._binary_catalog:
            binary_path = self._binary_catalog.get(
                (spec.release_id, spec.mediamtx_binary_sha256)
            )
            if binary_path is None:
                raise ValueError("node_release_not_allowed")
        if binary_path is None:
            return
        digest = _sha256_regular_file(binary_path)
        if digest != spec.mediamtx_binary_sha256:
            raise ValueError("node_binary_digest_mismatch")
        value = str(binary_path)
        if any(character.isspace() or character in "'\"\\" for character in value):
            raise ValueError("node_binary_path_unsafe")
        self._replace_private_file(
            node_fd,
            "runtime.env",
            f"RTSP_PROXY_MEDIAMTX_BINARY={value}\n".encode(),
        )

    def _replace_private_file(self, node_fd: int, name: str, payload: bytes) -> None:
        temporary_name = f".{name}.{secrets.token_hex(12)}.tmp"
        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
        if hasattr(os, "O_CLOEXEC"):
            flags |= os.O_CLOEXEC
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        descriptor = os.open(temporary_name, flags, 0o600, dir_fd=node_fd)
        try:
            offset = 0
            while offset < len(payload):
                written = os.write(descriptor, payload[offset:])
                if written <= 0:
                    raise OSError("short private file write")
                offset += written
            os.fchmod(descriptor, 0o600)
            os.fsync(descriptor)
        finally:
            os.close(descriptor)
        os.rename(temporary_name, name, src_dir_fd=node_fd, dst_dir_fd=node_fd)
        os.fsync(node_fd)

    def _read_private_file(self, node_fd: int, name: str) -> str:
        flags = os.O_RDONLY
        if hasattr(os, "O_CLOEXEC"):
            flags |= os.O_CLOEXEC
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        descriptor = os.open(name, flags, dir_fd=node_fd)
        try:
            file_stat = os.fstat(descriptor)
            if (
                not stat.S_ISREG(file_stat.st_mode)
                or stat.S_IMODE(file_stat.st_mode) != 0o600
                or file_stat.st_uid != self._owner_uid
                or file_stat.st_size > 4096
            ):
                raise ValueError("node_private_file_unsafe")
            payload = os.read(descriptor, 4097)
            if len(payload) > 4096:
                raise ValueError("node_private_file_unsafe")
            return payload.decode("utf-8")
        finally:
            os.close(descriptor)

    @staticmethod
    def _new_credentials(spec: NodeRuntimeSpec) -> NodeManagementCredentials:
        password = base64.urlsafe_b64encode(secrets.token_bytes(32)).decode("ascii").rstrip("=")
        return NodeManagementCredentials(
            username=f"node-{spec.node_id}",
            password=password,
        )

    @staticmethod
    def _new_reader_credentials(spec: NodeRuntimeSpec) -> NodeReaderCredentials:
        password = base64.urlsafe_b64encode(secrets.token_bytes(32)).decode("ascii").rstrip("=")
        return NodeReaderCredentials(
            username=f"reader-{spec.node_id}",
            password=password,
        )


@dataclass(frozen=True, slots=True)
class NodeProcessSnapshot:
    active: bool
    pid: int | None
    process_start_ticks: int | None
    boot_id: UUID | None
    executable_sha256: str | None

    def __post_init__(self) -> None:
        identity = (
            self.pid,
            self.process_start_ticks,
            self.boot_id,
            self.executable_sha256,
        )
        if self.active:
            if (
                self.pid is None
                or self.pid < 1
                or self.process_start_ticks is None
                or self.process_start_ticks < 1
                or self.boot_id is None
                or self.executable_sha256 is None
            ):
                raise ValueError("active_node_process_identity_incomplete")
        elif any(value is not None for value in identity):
            raise ValueError("inactive_node_process_has_identity")


class NodeProcessController(Protocol):
    def execute(
        self,
        action: NodeRuntimeAction,
        spec: NodeRuntimeSpec,
        deadline: NodeOperationDeadline | None = None,
    ) -> NodeProcessSnapshot: ...


class NodeSmokeProbe(Protocol):
    def check(
        self,
        spec: NodeRuntimeSpec,
        credentials: NodeManagementCredentials,
        deadline: NodeOperationDeadline | None = None,
    ) -> None: ...


class NodeSupervisorError(RuntimeError):
    """A scoped media-node lifecycle operation failed closed."""


class LinuxNodeSupervisor:
    """Own config, exact process operation, identity and smoke as one module."""

    _STOP_CONVERGENCE_ATTEMPTS = 21
    _STOP_CONVERGENCE_DELAY_SECONDS = 0.05

    def __init__(
        self,
        *,
        config_store: SecureNodeConfigStore,
        process: NodeProcessController,
        smoke: NodeSmokeProbe,
        port_is_bindable: Callable[[int], bool],
        smoke_attempts: int = 1,
        retry_delay_seconds: float = 0,
        sleep: Callable[[float], None] = time.sleep,
    ) -> None:
        if smoke_attempts < 1 or smoke_attempts > 120:
            raise ValueError("node_smoke_attempts_invalid")
        if retry_delay_seconds < 0 or retry_delay_seconds > 5:
            raise ValueError("node_smoke_retry_delay_invalid")
        self._config_store = config_store
        self._process = process
        self._smoke = smoke
        self._port_is_bindable = port_is_bindable
        self._smoke_attempts = smoke_attempts
        self._retry_delay_seconds = retry_delay_seconds
        self._sleep = sleep

    def execute(
        self,
        command: NodeRuntimeCommand,
        *,
        deadline: NodeOperationDeadline | None = None,
        cleanup_reserve_seconds: float = 3,
    ) -> NodeRuntimeObservation:
        from rtsp_proxy.nodes import NodeHealth, NodeRuntimeObservation, NodeState

        mutating = command.action in {
            NodeRuntimeAction.PROVISION_START,
            NodeRuntimeAction.START,
            NodeRuntimeAction.RESTART,
        }
        work_deadline = deadline
        if deadline is not None:
            work_deadline = (
                deadline.before(cleanup_reserve_seconds) if mutating else deadline
            )
            work_deadline.remaining_seconds()

        expected: RenderedNodeConfig | None
        credentials: NodeManagementCredentials | None
        if command.action is NodeRuntimeAction.PROVISION_START:
            expected, credentials = self._config_store.provision(command.spec)
        else:
            expected_state = self._config_store.expected(command.spec)
            expected, credentials = (None, None) if expected_state is None else expected_state
            if command.action in {NodeRuntimeAction.START, NodeRuntimeAction.RESTART}:
                self._config_store.rebind_release(command.spec)
        installed_sha256 = self._config_store.digest(command.spec)
        if command.action in {
            NodeRuntimeAction.PROVISION_START,
            NodeRuntimeAction.START,
            NodeRuntimeAction.RESTART,
        } and (
            expected is None or credentials is None or installed_sha256 != expected.sha256
        ):
            raise NodeSupervisorError("node_config_not_applied")

        try:
            if work_deadline is not None:
                work_deadline.remaining_seconds()
            snapshot = self._process.execute(command.action, command.spec, work_deadline)
            if command.action is NodeRuntimeAction.STOP:
                self._require_stopped(command.spec, snapshot, deadline)
                return self._stopped_observation(
                    command.spec,
                    installed_sha256=installed_sha256,
                    expected_sha256=None if expected is None else expected.sha256,
                )
            if command.action is NodeRuntimeAction.OBSERVE and not snapshot.active:
                return self._stopped_observation(
                    command.spec,
                    installed_sha256=installed_sha256,
                    expected_sha256=None if expected is None else expected.sha256,
                )
            if expected is None or credentials is None or installed_sha256 != expected.sha256:
                raise NodeSupervisorError("node_config_not_applied")
            if not snapshot.active:
                raise NodeSupervisorError("node_process_not_active")
            if snapshot.executable_sha256 != command.spec.mediamtx_binary_sha256:
                raise NodeSupervisorError("node_process_release_mismatch")
            assert credentials is not None
            self._run_smoke(command.spec, credentials, work_deadline)
            after_smoke = self._process.execute(
                NodeRuntimeAction.OBSERVE,
                command.spec,
                work_deadline,
            )
            if after_smoke != snapshot:
                raise NodeSupervisorError("node_process_identity_changed")
        except NodeSupervisorError:
            if not mutating:
                raise
            try:
                stopped = self._process.execute(
                    NodeRuntimeAction.STOP,
                    command.spec,
                    deadline,
                )
                self._require_stopped(command.spec, stopped, deadline)
            except Exception as cleanup_error:
                raise NodeSupervisorError("node_start_failed_cleanup_failed") from cleanup_error
            raise
        return NodeRuntimeObservation(
            state=NodeState.RUNNING,
            health=NodeHealth.HEALTHY,
            management_fresh=True,
            config_compatible=True,
            applied_revision=command.spec.desired_revision,
            process_id=snapshot.pid,
            process_start_ticks=snapshot.process_start_ticks,
            process_boot_id=snapshot.boot_id,
            config_sha256=installed_sha256,
            release_id=command.spec.release_id,
        )

    def _require_stopped(
        self,
        spec: NodeRuntimeSpec,
        snapshot: NodeProcessSnapshot,
        deadline: NodeOperationDeadline | None = None,
    ) -> None:
        if snapshot.active:
            raise NodeSupervisorError("node_process_still_active")
        ports = (spec.external_port, spec.api_port, spec.metrics_port)
        for attempt in range(self._STOP_CONVERGENCE_ATTEMPTS):
            available = tuple(self._port_is_bindable(port) for port in ports)
            if all(available):
                return
            if attempt + 1 < self._STOP_CONVERGENCE_ATTEMPTS:
                delay = self._STOP_CONVERGENCE_DELAY_SECONDS
                if deadline is not None:
                    delay = min(delay, deadline.remaining_seconds())
                self._sleep(delay)
        raise NodeSupervisorError("node_listener_still_active")

    @staticmethod
    def _stopped_observation(
        spec: NodeRuntimeSpec,
        *,
        installed_sha256: str | None,
        expected_sha256: str | None,
    ) -> NodeRuntimeObservation:
        compatible = expected_sha256 is not None and installed_sha256 == expected_sha256
        return NodeRuntimeObservation(
            state=NodeState.STOPPED,
            health=NodeHealth.UNKNOWN,
            config_compatible=compatible,
            applied_revision=spec.desired_revision if compatible else 0,
            config_sha256=installed_sha256,
            release_id=spec.release_id,
        )

    def _run_smoke(
        self,
        spec: NodeRuntimeSpec,
        credentials: NodeManagementCredentials,
        deadline: NodeOperationDeadline | None,
    ) -> None:
        last_error: NodeSupervisorError | None = None
        for attempt in range(self._smoke_attempts):
            try:
                self._smoke.check(spec, credentials, deadline)
                return
            except NodeSupervisorError as error:
                last_error = error
                if attempt + 1 < self._smoke_attempts:
                    delay = self._retry_delay_seconds
                    if deadline is not None:
                        delay = min(delay, deadline.remaining_seconds())
                    self._sleep(delay)
        assert last_error is not None
        raise last_error


class MediaNodeSmokeProbe:
    """Prove exact API, metrics and ordinary RTSP/TCP listeners."""

    def __init__(self, *, timeout_seconds: float) -> None:
        if timeout_seconds <= 0 or timeout_seconds > 10:
            raise ValueError("node_smoke_timeout_invalid")
        self._timeout_seconds = timeout_seconds

    def check(
        self,
        spec: NodeRuntimeSpec,
        credentials: NodeManagementCredentials,
        deadline: NodeOperationDeadline | None = None,
    ) -> None:
        config = self._read_http(
            f"http://127.0.0.1:{spec.api_port}/v3/config/global/get",
            "node_api_smoke_failed",
            credentials,
            deadline,
        )
        try:
            actual = json.loads(config)
        except (UnicodeError, json.JSONDecodeError) as error:
            raise NodeSupervisorError("node_api_smoke_failed") from error
        if not isinstance(actual, dict) or not self._global_config_matches(actual, spec):
            raise NodeSupervisorError("node_api_config_mismatch")
        self._read_http(
            f"http://127.0.0.1:{spec.metrics_port}/metrics",
            "node_metrics_smoke_failed",
            credentials,
            deadline,
        )
        self._check_rtsp(spec.external_port, deadline)

    def _read_http(
        self,
        url: str,
        error_code: str,
        credentials: NodeManagementCredentials,
        deadline: NodeOperationDeadline | None,
    ) -> str:
        request = urllib.request.Request(url, method="GET")
        token = base64.b64encode(f"{credentials.username}:{credentials.password}".encode()).decode(
            "ascii"
        )
        request.add_header("Authorization", f"Basic {token}")
        try:
            timeout = self._operation_timeout(deadline)
            with urllib.request.urlopen(request, timeout=timeout) as response:
                content = bytes(response.read(1024 * 1024 + 1))
        except (OSError, urllib.error.HTTPError, urllib.error.URLError) as error:
            raise NodeSupervisorError(error_code) from error
        if len(content) > 1024 * 1024:
            raise NodeSupervisorError(error_code)
        try:
            return content.decode("utf-8")
        except UnicodeError as error:
            raise NodeSupervisorError(error_code) from error

    @staticmethod
    def _global_config_matches(actual: dict[str, object], spec: NodeRuntimeSpec) -> bool:
        return (
            actual.get("api") is True
            and actual.get("apiAddress") == f"127.0.0.1:{spec.api_port}"
            and actual.get("metrics") is True
            and actual.get("metricsAddress") == f"127.0.0.1:{spec.metrics_port}"
            and actual.get("rtsp") is True
            and actual.get("rtspAddress") == f":{spec.external_port}"
            and actual.get("rtspTransports") == ["tcp"]
            and actual.get("rtspEncryption") == "no"
            and actual.get("rtmp") is False
            and actual.get("hls") is False
            and actual.get("webrtc") is False
            and actual.get("srt") is False
        )

    def _check_rtsp(
        self,
        port: int,
        deadline: NodeOperationDeadline | None,
    ) -> None:
        request = (
            f"OPTIONS rtsp://127.0.0.1:{port}/ RTSP/1.0\r\n"
            "CSeq: 1\r\n"
            "User-Agent: rtsp-proxy-node-smoke/1\r\n\r\n"
        ).encode("ascii")
        try:
            with socket.create_connection(
                ("127.0.0.1", port),
                timeout=self._operation_timeout(deadline),
            ) as connection:
                connection.settimeout(self._operation_timeout(deadline))
                connection.sendall(request)
                response = bytearray()
                while b"\r\n\r\n" not in response:
                    chunk = connection.recv(4096)
                    if not chunk:
                        break
                    response.extend(chunk)
                    if len(response) > 8192:
                        raise NodeSupervisorError("node_rtsp_smoke_failed")
        except (OSError, TimeoutError) as error:
            raise NodeSupervisorError("node_rtsp_smoke_failed") from error
        first_line = bytes(response).partition(b"\r\n")[0].split()
        if (
            len(first_line) < 2
            or first_line[0] != b"RTSP/1.0"
            or len(first_line[1]) != 3
            or not first_line[1].isdigit()
        ):
            raise NodeSupervisorError("node_rtsp_smoke_failed")

    def _operation_timeout(self, deadline: NodeOperationDeadline | None) -> float:
        if deadline is None:
            return self._timeout_seconds
        return deadline.remaining_seconds(maximum=self._timeout_seconds)


CommandRunner = Callable[[tuple[str, ...], float], CompletedProcess[str]]
ProcessIdentityReader = Callable[[Path, int], NodeProcessSnapshot]


class SystemdNodeProcessController:
    """Translate a validated UUID spec into one exact systemd instance operation."""

    _EXEC_TRANSITION_ATTEMPTS = 101
    _EXEC_TRANSITION_DELAY_SECONDS = 0.01

    def __init__(
        self,
        *,
        systemctl: Path,
        run: CommandRunner | None = None,
        proc_root: Path = Path("/proc"),
        sleep: Callable[[float], None] = time.sleep,
    ) -> None:
        if not systemctl.is_absolute():
            raise ValueError("systemctl_path_must_be_absolute")
        self._systemctl = systemctl
        self._run = run or self._run_command
        self._proc_root = proc_root
        self._sleep = sleep

    def execute(
        self,
        action: NodeRuntimeAction,
        spec: NodeRuntimeSpec,
        deadline: NodeOperationDeadline | None = None,
    ) -> NodeProcessSnapshot:
        unit = f"rtsp-proxy-media@{spec.node_id}.service"
        verbs = {
            NodeRuntimeAction.PROVISION_START: "start",
            NodeRuntimeAction.START: "start",
            NodeRuntimeAction.STOP: "stop",
            NodeRuntimeAction.RESTART: "restart",
        }
        if action in verbs:
            command_deadline = (
                deadline.before(5)
                if action is NodeRuntimeAction.STOP and deadline is not None
                else deadline
            )
            self._checked_run(
                (
                    str(self._systemctl),
                    "--no-ask-password",
                    verbs[action],
                    unit,
                ),
                command_deadline,
            )
        result = self._checked_run(
            (
                str(self._systemctl),
                "--no-pager",
                "show",
                unit,
                "--property=ActiveState",
                "--property=MainPID",
            ),
            deadline,
        )
        properties = self._parse_properties(result.stdout)
        active_state = properties.get("ActiveState")
        raw_pid = properties.get("MainPID")
        if (
            active_state is None
            or raw_pid is None
            or not raw_pid.isascii()
            or not raw_pid.isdigit()
        ):
            raise NodeSupervisorError("systemd_node_status_invalid")
        pid = int(raw_pid)
        if active_state != "active":
            if pid != 0:
                raise NodeSupervisorError("systemd_inactive_node_has_pid")
            return NodeProcessSnapshot(
                active=False,
                pid=None,
                process_start_ticks=None,
                boot_id=None,
                executable_sha256=None,
            )
        if pid < 1:
            raise NodeSupervisorError("systemd_active_node_missing_pid")
        if action in {
            NodeRuntimeAction.PROVISION_START,
            NodeRuntimeAction.START,
            NodeRuntimeAction.RESTART,
        }:
            snapshot = self._wait_for_exec_transition(
                pid,
                spec.mediamtx_binary_sha256,
                deadline,
            )
        else:
            snapshot = self._read_process_identity(pid)
        repeated = self._checked_run(
            (
                str(self._systemctl),
                "--no-pager",
                "show",
                unit,
                "--property=ActiveState",
                "--property=MainPID",
            ),
            deadline,
        )
        repeated_properties = self._parse_properties(repeated.stdout)
        if repeated_properties != properties:
            raise NodeSupervisorError("systemd_node_identity_changed")
        return snapshot

    def _wait_for_exec_transition(
        self,
        pid: int,
        expected_sha256: str,
        deadline: NodeOperationDeadline | None,
    ) -> NodeProcessSnapshot:
        snapshot: NodeProcessSnapshot | None = None
        unavailable: NodeSupervisorError | None = None
        for attempt in range(self._EXEC_TRANSITION_ATTEMPTS):
            try:
                current = self._read_process_identity(pid)
            except NodeSupervisorError as error:
                if str(error) != "node_process_identity_unavailable":
                    raise
                unavailable = error
            else:
                if snapshot is not None and (
                    current.pid != snapshot.pid
                    or current.process_start_ticks != snapshot.process_start_ticks
                    or current.boot_id != snapshot.boot_id
                ):
                    raise NodeSupervisorError("systemd_node_identity_changed")
                snapshot = current
                if snapshot.executable_sha256 == expected_sha256:
                    return snapshot
            if attempt + 1 < self._EXEC_TRANSITION_ATTEMPTS:
                delay = self._EXEC_TRANSITION_DELAY_SECONDS
                if deadline is not None:
                    delay = min(delay, deadline.remaining_seconds())
                self._sleep(delay)
        if snapshot is not None:
            return snapshot
        assert unavailable is not None
        raise unavailable

    def _checked_run(
        self,
        arguments: tuple[str, ...],
        deadline: NodeOperationDeadline | None,
    ) -> CompletedProcess[str]:
        try:
            timeout = 30 if deadline is None else deadline.remaining_seconds(maximum=30)
            result = self._run(arguments, timeout)
        except (OSError, subprocess.TimeoutExpired) as error:
            raise NodeSupervisorError("systemd_node_command_failed") from error
        if result.returncode != 0:
            raise NodeSupervisorError("systemd_node_command_failed")
        return result

    @staticmethod
    def _run_command(arguments: tuple[str, ...], timeout: float) -> CompletedProcess[str]:
        return subprocess.run(
            arguments,
            check=False,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=timeout,
            env={"LC_ALL": "C", "PATH": os.defpath},
        )

    @staticmethod
    def _parse_properties(output: str) -> dict[str, str]:
        properties: dict[str, str] = {}
        for line in output.splitlines():
            key, separator, value = line.partition("=")
            if not separator or not key or key in properties:
                raise NodeSupervisorError("systemd_node_status_invalid")
            properties[key] = value
        return properties

    def _read_process_identity(self, pid: int) -> NodeProcessSnapshot:
        return _read_linux_process_identity(self._proc_root, pid)


class DirectNodeProcessController:
    """Native contract adapter: independent MediaMTX processes without systemd."""

    def __init__(
        self,
        *,
        mediamtx_binary: Path,
        config_root: Path,
        proc_root: Path = Path("/proc"),
        process_identity: ProcessIdentityReader | None = None,
    ) -> None:
        if not mediamtx_binary.is_absolute() or not mediamtx_binary.is_file():
            raise ValueError("mediamtx_binary_invalid")
        if not config_root.is_absolute():
            raise ValueError("node_config_root_must_be_absolute")
        self._mediamtx_binary = mediamtx_binary
        self._config_root = config_root
        self._proc_root = proc_root
        self._process_identity = process_identity or _read_linux_process_identity
        self._processes: dict[UUID, subprocess.Popen[bytes]] = {}

    def execute(
        self,
        action: NodeRuntimeAction,
        spec: NodeRuntimeSpec,
        deadline: NodeOperationDeadline | None = None,
    ) -> NodeProcessSnapshot:
        if deadline is not None:
            deadline.remaining_seconds()
        if action is NodeRuntimeAction.STOP:
            self._stop(spec.node_id, deadline)
            return self._inactive_snapshot()
        if action is NodeRuntimeAction.RESTART:
            self._stop(spec.node_id, deadline)
            self._start(spec)
        elif action in {NodeRuntimeAction.PROVISION_START, NodeRuntimeAction.START}:
            process = self._processes.get(spec.node_id)
            if process is None or process.poll() is not None:
                self._start(spec)
        process = self._processes.get(spec.node_id)
        if process is None or process.poll() is not None:
            return self._inactive_snapshot()
        return self._process_identity(self._proc_root, process.pid)

    def close(self) -> None:
        for node_id in tuple(self._processes):
            self._stop(node_id, None)

    def _start(self, spec: NodeRuntimeSpec) -> None:
        config = self._config_root / str(spec.node_id) / "mediamtx.yml"
        if not config.is_file() or config.is_symlink():
            raise NodeSupervisorError("node_config_not_applied")
        try:
            process = subprocess.Popen(
                (str(self._mediamtx_binary), str(config)),
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                close_fds=True,
                start_new_session=True,
                env={"LC_ALL": "C", "PATH": os.defpath},
            )
        except OSError as error:
            raise NodeSupervisorError("node_process_start_failed") from error
        self._processes[spec.node_id] = process

    def _stop(
        self,
        node_id: UUID,
        deadline: NodeOperationDeadline | None,
    ) -> None:
        process = self._processes.pop(node_id, None)
        if process is None or process.poll() is not None:
            return
        process.terminate()
        try:
            timeout = 10 if deadline is None else deadline.remaining_seconds(maximum=10)
            process.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            process.kill()
            try:
                timeout = 5 if deadline is None else deadline.remaining_seconds(maximum=5)
                process.wait(timeout=timeout)
            except subprocess.TimeoutExpired as error:
                raise NodeSupervisorError("node_process_stop_failed") from error

    @staticmethod
    def _inactive_snapshot() -> NodeProcessSnapshot:
        return NodeProcessSnapshot(
            active=False,
            pid=None,
            process_start_ticks=None,
            boot_id=None,
            executable_sha256=None,
        )


def _read_linux_process_identity(proc_root: Path, pid: int) -> NodeProcessSnapshot:
    process_root = proc_root / str(pid)
    try:
        stat_line = (process_root / "stat").read_text(encoding="ascii")
        closing_parenthesis = stat_line.rfind(")")
        fields = stat_line[closing_parenthesis + 2 :].split()
        if closing_parenthesis < 1 or len(fields) <= 19:
            raise ValueError
        process_start_ticks = int(fields[19])
        boot_id = UUID(
            (proc_root / "sys/kernel/random/boot_id").read_text(encoding="ascii").strip()
        )
        executable = (process_root / "exe").resolve(strict=True)
        digest = hashlib.sha256()
        with executable.open("rb") as binary:
            for chunk in iter(lambda: binary.read(1024 * 1024), b""):
                digest.update(chunk)
        repeated_stat_line = (process_root / "stat").read_text(encoding="ascii")
        repeated_closing_parenthesis = repeated_stat_line.rfind(")")
        repeated_fields = repeated_stat_line[repeated_closing_parenthesis + 2 :].split()
        if (
            repeated_closing_parenthesis < 1
            or len(repeated_fields) <= 19
            or int(repeated_fields[19]) != process_start_ticks
            or (process_root / "exe").resolve(strict=True) != executable
        ):
            raise ValueError
    except (OSError, UnicodeError, ValueError) as error:
        raise NodeSupervisorError("node_process_identity_unavailable") from error
    return NodeProcessSnapshot(
        active=True,
        pid=pid,
        process_start_ticks=process_start_ticks,
        boot_id=boot_id,
        executable_sha256=digest.hexdigest(),
    )


def _sha256_regular_file(path: Path) -> str:
    try:
        file_stat = path.stat(follow_symlinks=False)
        if not path.is_absolute() or not stat.S_ISREG(file_stat.st_mode):
            raise ValueError
        digest = hashlib.sha256()
        with path.open("rb") as artifact:
            for chunk in iter(lambda: artifact.read(1024 * 1024), b""):
                digest.update(chunk)
        return digest.hexdigest()
    except (OSError, ValueError) as error:
        raise ValueError("node_binary_path_unsafe") from error


_MAX_RUNTIME_MESSAGE_BYTES = 65536


class _RuntimeObservationPayload(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)

    state: NodeState
    health: NodeHealth
    management_fresh: bool
    config_compatible: bool
    applied_revision: int
    process_id: int | None
    process_start_ticks: int | None
    process_boot_id: UUID | None
    config_sha256: str | None
    release_id: str | None


class _RuntimeSpecPayload(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)

    node_id: UUID
    external_port: int
    api_port: int
    metrics_port: int
    desired_revision: int
    release_id: str
    mediamtx_binary_sha256: str


class _RuntimeConfigPayload(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)

    content: str
    sha256: str


class _RuntimeRequestPayload(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)

    schema_version: int
    action: NodeRuntimeAction
    spec: _RuntimeSpecPayload
    config: _RuntimeConfigPayload | None
    deadline_unix_ms: int | None = Field(default=None, ge=1)


class _RuntimeResponsePayload(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)

    schema_version: int
    ok: bool
    observation: _RuntimeObservationPayload | None
    error: str | None


class UnixNodeRuntimeClient:
    """Control-plane adapter for the root-owned, UUID-scoped local helper."""

    def __init__(self, *, socket_path: Path, timeout_seconds: float) -> None:
        if not socket_path.is_absolute():
            raise ValueError("node_runtime_socket_must_be_absolute")
        if timeout_seconds <= 0 or timeout_seconds > 60:
            raise ValueError("node_runtime_timeout_invalid")
        self._socket_path = socket_path
        self._timeout_seconds = timeout_seconds

    def execute(
        self,
        action: NodeRuntimeAction,
        node: MediaNode,
    ) -> NodeRuntimeObservation:
        spec = NodeRuntimeSpec(
            node_id=node.id,
            external_port=node.external_port,
            api_port=node.api_port,
            metrics_port=node.metrics_port,
            desired_revision=node.desired_revision,
            release_id=node.release_id,
            mediamtx_binary_sha256=node.mediamtx_binary_sha256,
        )
        command = NodeRuntimeCommand.for_node(action, spec)
        response_reserve = min(1.0, self._timeout_seconds / 2)
        deadline_unix_ms = int(
            (time.time() + self._timeout_seconds - response_reserve) * 1000
        )
        request = self._encode_command(command, deadline_unix_ms=deadline_unix_ms)
        try:
            with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as connection:
                connection.settimeout(self._timeout_seconds)
                connection.connect(str(self._socket_path))
                connection.sendall(request)
                response = connection.makefile("rb").readline(_MAX_RUNTIME_MESSAGE_BYTES + 1)
        except (OSError, TimeoutError) as error:
            raise NodeSupervisorError("node_runtime_unavailable") from error
        if (
            not response
            or len(response) > _MAX_RUNTIME_MESSAGE_BYTES
            or not response.endswith(b"\n")
        ):
            raise NodeSupervisorError("node_runtime_response_invalid")
        try:
            payload = _RuntimeResponsePayload.model_validate_json(response)
        except ValidationError as error:
            raise NodeSupervisorError("node_runtime_response_invalid") from error
        if payload.schema_version != 1:
            raise NodeSupervisorError("node_runtime_response_invalid")
        if not payload.ok:
            if payload.observation is not None or payload.error is None:
                raise NodeSupervisorError("node_runtime_response_invalid")
            raise NodeSupervisorError(payload.error)
        if payload.observation is None or payload.error is not None:
            raise NodeSupervisorError("node_runtime_response_invalid")
        observation = payload.observation
        return NodeRuntimeObservation(
            state=observation.state,
            health=observation.health,
            management_fresh=observation.management_fresh,
            config_compatible=observation.config_compatible,
            applied_revision=observation.applied_revision,
            process_id=observation.process_id,
            process_start_ticks=observation.process_start_ticks,
            process_boot_id=observation.process_boot_id,
            config_sha256=observation.config_sha256,
            release_id=observation.release_id,
        )

    @staticmethod
    def _encode_command(
        command: NodeRuntimeCommand,
        *,
        deadline_unix_ms: int,
    ) -> bytes:
        payload = {
            "schema_version": 1,
            "action": command.action.value,
            "spec": {
                "node_id": str(command.spec.node_id),
                "external_port": command.spec.external_port,
                "api_port": command.spec.api_port,
                "metrics_port": command.spec.metrics_port,
                "desired_revision": command.spec.desired_revision,
                "release_id": command.spec.release_id,
                "mediamtx_binary_sha256": command.spec.mediamtx_binary_sha256,
            },
            "config": None,
            "deadline_unix_ms": deadline_unix_ms,
        }
        encoded = (json.dumps(payload, separators=(",", ":"), sort_keys=True) + "\n").encode(
            "utf-8"
        )
        if len(encoded) > _MAX_RUNTIME_MESSAGE_BYTES:
            raise NodeSupervisorError("node_runtime_request_too_large")
        return encoded


@dataclass(frozen=True, slots=True)
class NodeRuntimePolicy:
    external_port_start: int
    external_port_end: int
    api_port_start: int
    api_port_end: int
    metrics_port_start: int
    metrics_port_end: int
    release_id: str
    mediamtx_binary_sha256: str
    previous_release_id: str | None = None
    previous_mediamtx_binary_sha256: str | None = None

    def validate(self, spec: NodeRuntimeSpec) -> None:
        if not self.external_port_start <= spec.external_port <= self.external_port_end:
            raise NodeSupervisorError("node_external_port_not_allowed")
        if not self.api_port_start <= spec.api_port <= self.api_port_end:
            raise NodeSupervisorError("node_api_port_not_allowed")
        if not self.metrics_port_start <= spec.metrics_port <= self.metrics_port_end:
            raise NodeSupervisorError("node_metrics_port_not_allowed")
        allowed = {
            (self.release_id, self.mediamtx_binary_sha256),
        }
        if self.previous_release_id is not None:
            if self.previous_mediamtx_binary_sha256 is None:
                raise NodeSupervisorError("node_release_policy_invalid")
            allowed.add(
                (self.previous_release_id, self.previous_mediamtx_binary_sha256)
            )
        if (spec.release_id, spec.mediamtx_binary_sha256) not in allowed:
            raise NodeSupervisorError("node_release_not_allowed")


class _ScopedNodeLock:
    def __init__(
        self,
        *,
        node_id: UUID,
        guard: Lock,
        locks: dict[UUID, tuple[Lock, int]],
    ) -> None:
        self._node_id = node_id
        self._guard = guard
        self._locks = locks
        self._lock: Lock | None = None

    def __enter__(self) -> None:
        with self._guard:
            lock, references = self._locks.get(self._node_id, (Lock(), 0))
            self._locks[self._node_id] = (lock, references + 1)
            self._lock = lock
        lock.acquire()

    def __exit__(self, *exc_info: object) -> None:
        assert self._lock is not None
        self._lock.release()
        with self._guard:
            lock, references = self._locks[self._node_id]
            assert lock is self._lock and references > 0
            if references == 1:
                del self._locks[self._node_id]
            else:
                self._locks[self._node_id] = (lock, references - 1)


class UnixNodeSupervisorServer:
    """Root-side one-request protocol with an allowlisted node policy."""

    def __init__(
        self,
        *,
        supervisor: LinuxNodeSupervisor,
        policy: NodeRuntimePolicy,
        request_timeout_seconds: float = 5,
        operation_timeout_seconds: float = 55,
        cleanup_reserve_seconds: float = 25,
        max_workers: int = 16,
        wall_time: Callable[[], float] = time.time,
        monotonic: Callable[[], float] = time.monotonic,
    ) -> None:
        if request_timeout_seconds <= 0 or request_timeout_seconds > 30:
            raise ValueError("node_runtime_request_timeout_invalid")
        if operation_timeout_seconds <= 0 or operation_timeout_seconds > 55:
            raise ValueError("node_runtime_operation_timeout_invalid")
        if cleanup_reserve_seconds < 20 or cleanup_reserve_seconds >= operation_timeout_seconds:
            raise ValueError("node_runtime_cleanup_reserve_invalid")
        if max_workers < 1 or max_workers > 64:
            raise ValueError("node_runtime_workers_invalid")
        self._supervisor = supervisor
        self._policy = policy
        self._request_timeout_seconds = request_timeout_seconds
        self._operation_timeout_seconds = operation_timeout_seconds
        self._cleanup_reserve_seconds = cleanup_reserve_seconds
        self._max_workers = max_workers
        self._wall_time = wall_time
        self._monotonic = monotonic
        self._node_locks_guard = Lock()
        self._node_locks: dict[UUID, tuple[Lock, int]] = {}

    def serve_connection(self, connection: socket.socket) -> None:
        try:
            connection.settimeout(self._request_timeout_seconds)
            request = connection.makefile("rb").readline(_MAX_RUNTIME_MESSAGE_BYTES + 1)
            command, requested_deadline_unix_ms = self._decode_command(request)
            self._policy.validate(command.spec)
            deadline = self._operation_deadline(requested_deadline_unix_ms)
            with self._node_lock(command.spec.node_id):
                observation = self._supervisor.execute(
                    command,
                    deadline=deadline,
                    cleanup_reserve_seconds=self._cleanup_reserve_seconds,
                )
            payload = self._success_payload(observation)
        except NodeSupervisorError as error:
            payload = self._error_payload(str(error))
        except (OSError, TimeoutError):
            payload = self._error_payload("node_runtime_request_timeout")
        except Exception:
            payload = self._error_payload("node_runtime_internal_error")
        encoded = (json.dumps(payload, separators=(",", ":"), sort_keys=True) + "\n").encode(
            "utf-8"
        )
        with suppress(OSError, TimeoutError):
            connection.sendall(encoded)

    def serve_forever(self, listener: socket.socket) -> None:
        capacity = BoundedSemaphore(self._max_workers)
        with ThreadPoolExecutor(max_workers=self._max_workers) as workers:
            while True:
                capacity.acquire()
                try:
                    connection, _ = listener.accept()
                except BaseException:
                    capacity.release()
                    raise
                workers.submit(self._serve_owned_connection, connection, capacity)

    def _serve_owned_connection(
        self,
        connection: socket.socket,
        capacity: BoundedSemaphore,
    ) -> None:
        try:
            with connection:
                self.serve_connection(connection)
        finally:
            capacity.release()

    def _node_lock(self, node_id: UUID) -> _ScopedNodeLock:
        return _ScopedNodeLock(
            node_id=node_id,
            guard=self._node_locks_guard,
            locks=self._node_locks,
        )

    def _operation_deadline(
        self,
        requested_deadline_unix_ms: int | None,
    ) -> NodeOperationDeadline:
        maximum = self._operation_timeout_seconds
        if requested_deadline_unix_ms is not None:
            requested = requested_deadline_unix_ms / 1000 - self._wall_time()
            if requested <= 0:
                raise NodeSupervisorError("node_runtime_operation_timeout")
            maximum = min(maximum, requested)
        return NodeOperationDeadline(
            expires_monotonic=self._monotonic() + maximum,
            monotonic=self._monotonic,
        )

    @staticmethod
    def _decode_command(
        request: bytes,
    ) -> tuple[NodeRuntimeCommand, int | None]:
        if not request or len(request) > _MAX_RUNTIME_MESSAGE_BYTES or not request.endswith(b"\n"):
            raise NodeSupervisorError("node_runtime_request_invalid")
        try:
            payload = _RuntimeRequestPayload.model_validate_json(request)
        except ValidationError as error:
            raise NodeSupervisorError("node_runtime_request_invalid") from error
        if payload.schema_version != 1:
            raise NodeSupervisorError("node_runtime_request_invalid")
        try:
            spec = NodeRuntimeSpec(
                node_id=payload.spec.node_id,
                external_port=payload.spec.external_port,
                api_port=payload.spec.api_port,
                metrics_port=payload.spec.metrics_port,
                desired_revision=payload.spec.desired_revision,
                release_id=payload.spec.release_id,
                mediamtx_binary_sha256=payload.spec.mediamtx_binary_sha256,
            )
            config = (
                None
                if payload.config is None
                else RenderedNodeConfig(
                    content=payload.config.content,
                    sha256=payload.config.sha256,
                )
            )
            return (
                NodeRuntimeCommand(action=payload.action, spec=spec, config=config),
                payload.deadline_unix_ms,
            )
        except ValueError as error:
            raise NodeSupervisorError("node_runtime_request_invalid") from error

    @staticmethod
    def _success_payload(observation: NodeRuntimeObservation) -> dict[str, object]:
        return {
            "schema_version": 1,
            "ok": True,
            "observation": {
                "state": observation.state.value,
                "health": observation.health.value,
                "management_fresh": observation.management_fresh,
                "config_compatible": observation.config_compatible,
                "applied_revision": observation.applied_revision,
                "process_id": observation.process_id,
                "process_start_ticks": observation.process_start_ticks,
                "process_boot_id": (
                    None
                    if observation.process_boot_id is None
                    else str(observation.process_boot_id)
                ),
                "config_sha256": observation.config_sha256,
                "release_id": observation.release_id,
            },
            "error": None,
        }

    @staticmethod
    def _error_payload(error: str) -> dict[str, object]:
        return {
            "schema_version": 1,
            "ok": False,
            "observation": None,
            "error": error,
        }


class NodeHelperSettings(BaseSettings):
    model_config = SettingsConfigDict(
        env_prefix="RTSP_PROXY_NODE_HELPER_",
        extra="forbid",
        frozen=True,
    )

    config_root: Path = Path("/etc/rtsp-proxy/nodes")
    systemctl: Path = Path("/usr/bin/systemctl")
    mediamtx_binary: Path
    external_port_start: int = Field(ge=1, le=65535)
    external_port_end: int = Field(ge=1, le=65535)
    api_port_start: int = Field(ge=1, le=65535)
    api_port_end: int = Field(ge=1, le=65535)
    metrics_port_start: int = Field(ge=1, le=65535)
    metrics_port_end: int = Field(ge=1, le=65535)
    release_id: str = Field(pattern=r"^[0-9A-Za-z][0-9A-Za-z._-]{0,127}$")
    mediamtx_binary_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    previous_mediamtx_binary: Path | None = None
    previous_release_id: str | None = Field(
        default=None,
        pattern=r"^[0-9A-Za-z][0-9A-Za-z._-]{0,127}$",
    )
    previous_mediamtx_binary_sha256: str | None = Field(
        default=None,
        pattern=r"^[0-9a-f]{64}$",
    )
    smoke_timeout_seconds: float = Field(default=1, gt=0, le=10)
    smoke_attempts: int = Field(default=30, ge=1, le=120)
    smoke_retry_delay_seconds: float = Field(default=0.25, ge=0, le=5)
    request_timeout_seconds: float = Field(default=5, gt=0, le=30)
    operation_timeout_seconds: float = Field(default=55, gt=0, le=55)
    cleanup_reserve_seconds: float = Field(default=25, ge=20, le=30)
    max_workers: int = Field(default=16, ge=1, le=64)

    @model_validator(mode="after")
    def validate_policy(self) -> NodeHelperSettings:
        ranges = (
            (self.external_port_start, self.external_port_end),
            (self.api_port_start, self.api_port_end),
            (self.metrics_port_start, self.metrics_port_end),
        )
        if any(start > end for start, end in ranges):
            raise ValueError("node_helper_port_range_invalid")
        sets = tuple(set(range(start, end + 1)) for start, end in ranges)
        if sets[0] & sets[1] or sets[0] & sets[2] or sets[1] & sets[2]:
            raise ValueError("node_helper_port_ranges_overlap")
        if (
            not self.config_root.is_absolute()
            or not self.systemctl.is_absolute()
            or not self.mediamtx_binary.is_absolute()
        ):
            raise ValueError("node_helper_path_invalid")
        previous = (
            self.previous_mediamtx_binary,
            self.previous_release_id,
            self.previous_mediamtx_binary_sha256,
        )
        if any(value is not None for value in previous) and not all(
            value is not None for value in previous
        ):
            raise ValueError("node_helper_previous_release_incomplete")
        if self.previous_mediamtx_binary is not None:
            if not self.previous_mediamtx_binary.is_absolute():
                raise ValueError("node_helper_path_invalid")
            if self.previous_release_id == self.release_id:
                raise ValueError("node_helper_previous_release_duplicate")
        if self.cleanup_reserve_seconds >= self.operation_timeout_seconds:
            raise ValueError("node_runtime_cleanup_reserve_invalid")
        return self

    def policy(self) -> NodeRuntimePolicy:
        return NodeRuntimePolicy(
            external_port_start=self.external_port_start,
            external_port_end=self.external_port_end,
            api_port_start=self.api_port_start,
            api_port_end=self.api_port_end,
            metrics_port_start=self.metrics_port_start,
            metrics_port_end=self.metrics_port_end,
            release_id=self.release_id,
            mediamtx_binary_sha256=self.mediamtx_binary_sha256,
            previous_release_id=self.previous_release_id,
            previous_mediamtx_binary_sha256=(
                self.previous_mediamtx_binary_sha256
            ),
        )


def run_node_runtime_helper() -> None:
    settings = NodeHelperSettings()  # type: ignore[call-arg]
    listener = _systemd_activation_listener()
    supervisor = LinuxNodeSupervisor(
        config_store=SecureNodeConfigStore(
            root=settings.config_root,
            owner_uid=0,
            binary_catalog={
                (release_id, digest): binary
                for release_id, digest, binary in (
                    (
                        settings.release_id,
                        settings.mediamtx_binary_sha256,
                        settings.mediamtx_binary,
                    ),
                    (
                        settings.previous_release_id,
                        settings.previous_mediamtx_binary_sha256,
                        settings.previous_mediamtx_binary,
                    ),
                )
                if release_id is not None and digest is not None and binary is not None
            },
        ),
        process=SystemdNodeProcessController(systemctl=settings.systemctl),
        smoke=MediaNodeSmokeProbe(timeout_seconds=settings.smoke_timeout_seconds),
        port_is_bindable=_loopback_and_wildcard_port_is_bindable,
        smoke_attempts=settings.smoke_attempts,
        retry_delay_seconds=settings.smoke_retry_delay_seconds,
    )
    UnixNodeSupervisorServer(
        supervisor=supervisor,
        policy=settings.policy(),
        request_timeout_seconds=settings.request_timeout_seconds,
        operation_timeout_seconds=settings.operation_timeout_seconds,
        cleanup_reserve_seconds=settings.cleanup_reserve_seconds,
        max_workers=settings.max_workers,
    ).serve_forever(listener)


def _systemd_activation_listener() -> socket.socket:
    try:
        listen_pid = int(os.environ.get("LISTEN_PID", "0"))
        listen_fds = int(os.environ.get("LISTEN_FDS", "0"))
    except ValueError as error:
        raise SystemExit("node_helper_socket_activation_invalid") from error
    if listen_pid != os.getpid() or listen_fds != 1:
        raise SystemExit("node_helper_socket_activation_invalid")
    try:
        listener = socket.socket(fileno=3)
    except OSError as error:
        raise SystemExit("node_helper_socket_activation_invalid") from error
    if listener.family != socket.AF_UNIX or listener.type & socket.SOCK_STREAM == 0:
        listener.close()
        raise SystemExit("node_helper_socket_activation_invalid")
    return listener


def _loopback_and_wildcard_port_is_bindable(port: int) -> bool:
    probes = (
        (socket.AF_INET, "0.0.0.0"),
        (socket.AF_INET6, "::"),
    )
    for family, address in probes:
        try:
            with socket.socket(family, socket.SOCK_STREAM) as listener:
                listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
                if family is socket.AF_INET6:
                    listener.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 1)
                listener.bind((address, port))
        except OSError as error:
            if family is socket.AF_INET6 and error.errno in {
                errno.EAFNOSUPPORT,
                errno.EPROTONOSUPPORT,
                errno.EADDRNOTAVAIL,
            }:
                continue
            return False
    return True
