d /etc/rtsp-proxy 0755 root root -
d /etc/rtsp-proxy/control-plane 0750 root rtsp-proxy-access -
d /etc/rtsp-proxy/mediamtx 0750 root mediamtx -
d /etc/rtsp-proxy/nodes 0700 root root -
d /opt/rtsp-proxy/releases 0755 root root -
d /var/lib/rtsp-proxy 0750 rtsp-proxy rtsp-proxy -
d /var/log/rtsp-proxy 0750 rtsp-proxy rtsp-proxy -
d /var/lib/rtsp-proxy/nodes 0750 mediamtx mediamtx -
d /var/log/rtsp-proxy/nodes 0750 mediamtx mediamtx -
d /var/lib/mediamtx 0750 mediamtx mediamtx -
d /var/log/mediamtx 0750 mediamtx mediamtx -
d /run/rtsp-proxy-node-runtime 0750 root rtsp-proxy -
d /run/rtsp-proxy-node-metrics 0750 root rtsp-proxy-collector -
