d /etc/rtsp-proxy 0750 root rtsp-proxy -
d /opt/rtsp-proxy/releases 0755 root root -
d /var/lib/rtsp-proxy 0750 rtsp-proxy rtsp-proxy -
d /var/log/rtsp-proxy 0750 rtsp-proxy rtsp-proxy -
d /var/lib/mediamtx 0750 mediamtx mediamtx -
d /var/log/mediamtx 0750 mediamtx mediamtx -
